### ISSUE TITLE
Shiftclicking stuff out of Auto Chisel is buggy

### ISSUE THREAD

**Issue by VictiniX888** [TheCricket/Chisel-2#109]
Instead of their corresponding slots.

Chisel version: commit 389aa4e7117e48fd4b02c2b21a56928dd42b7590
Forge version: 1277

**Comment by warlordjones** [comment]
Fixed for next version by @tterrag1098 in his rewrite I presume

**Comment by CptSpaceToaster** [comment]
The commit indicates that VictiniX888 had built from source, and noticed a bug occurring after the change was put into effect.

**Comment by warlordjones** [comment]
whoops, so it does. Well spotted!

**Comment by VictiniX888** [comment]
So... updating this issue...
Anything can be shiftclicked into the Auto Chisel.
Tested with: commit c2eae121bc08fc9369a5e7ea1acea6f496dd83bd

**Comment by tterrag1098** [comment]
*sigh*

**Comment by VictiniX888** [comment]
When shiftclicking stuff out of the Auto Chisel, it goes into the slots in this order:
Last inventory slot (AKA bottom-left inventory slot, not hotbar)
Hotbar slot 1 - 8 (9 isn't used)
If all those slots are occupied, the stuff won't get shiftclicked into the inventory.

**Comment by tterrag1098** [comment]
Fixed **again** 5486eded3f0f67a37aa2c7dd4992c1a7f10a928f
