### ISSUE TITLE
Autochisel automation: extraction not working

### ISSUE THREAD

**Issue by VictiniX888** [TheCricket/Chisel-2#110]
With an Automation Upgrade.

Chisel verison: commit 5cf9829e0c78ee1b10a94ec621584fc344328acd
Forge version: 1277

**Comment by tterrag1098** [comment]
Is it meant to? I wasn't aware. Nothing in the code suggests that it is.

**Comment by VictiniX888** [comment]
The tooltip says it let's stuff push in and pull out of it.
Anyways, upgrades are COMPLETELY broken. I'm closing this and creating another issue.

**Comment by VictiniX888** [comment]
![2015-01-09_09 29 22](https://cloud.githubusercontent.com/assets/9777462/5674253/62d37a9e-97e2-11e4-91e4-98dccd0413e9.png)

**Comment by VictiniX888** [comment]
Okay. For some reason EnderIO Item Conduits don't work.
Item Buffers can pull items out, but they pull out of the left slot, not the right slot.
