### ISSUE TITLE
Mine painter crash

### ISSUE THREAD

**Issue by goldensecret** [TheCricket/Chisel-2#112]
openeye.openmods.info/crashes/bba0c6fbe6cdcfab88360b36da8c4db8

mine painter, is most likely the problem but the mod author dose not seem to be responding to contact attempts with this bug from other people, it occurs when you try to take a "chip" out of one of the converted blocks from chisel. and now the world will not open.

sorry if this is the wrong place to post bugs, couldn't think of anywhere else better otherwise :)

-thx

**Comment by warlordjones** [comment]
This is definitely the right place to post bugs! Could you add the bug label? I would, but I've had my perms removed.

**Comment by tterrag1098** [comment]
Poster can't assign labels, only contributors.

**Comment by tterrag1098** [comment]
You are extremely out of date, you are using the old chisel 1. Please update here: http://minecraft.curseforge.com/mc-mods/225236-chisel-2

**Comment by goldensecret** [comment]
sadly, this has not helped :( 

openeye.openmods.info/crashes/b5ac733aefc91ef490903c7ec3eaf989

**Comment by tterrag1098** [comment]
This is an issue with MinePainter. They should be calling the render function with the underlying block, not their own. Report it to themm
