### ISSUE TITLE
Crash placing EnderIO travel anchor surrounded by chiseled cobblestone

### ISSUE THREAD

**Issue by skermajo** [TheCricket/Chisel-2#113]
http://pastebin.com/yT5Nbvde

Just placing a Travel Anchor into a hole, surrounded by large cobblestone tiles. The world now crashes on load as well.

This is a build I built myself using unmodified source at this commit: https://github.com/TheCricket/Chisel-2/commit/f1d741685ed9c9441d7dbe579b3b775c4122a5f2

EnderIO v 2.2.6.321

e.g. placing anchor here will crash:
![2015-01-09_11 17 20](https://cloud.githubusercontent.com/assets/379441/5674116/3728c174-97f1-11e4-8bd7-ebd1f4dbe4cf.png)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/TheCricket/Chisel-2/commit/ab67cff7f316cc83d6157ec86049ffee541e276a
