### ISSUE TITLE
Hex plating problem

### ISSUE THREAD

**Issue by JadeCreeper** [TheCricket/Chisel-2#121]
Hex plating blocks are tile-entitys, So when i use a facade, it only renders the hexagons, and it can't be used on carpenter's blocks.

**Comment by tterrag1098** [comment]
It's not a TE, it just has custom rendering. Not sure why the facade couldn't support it.

**Comment by CptSpaceToaster** [comment]
Hex plating blocks are normal blocks that implement a slightly customized ISBRH, which does two things:
1. It makes a call to the standard block renderer which draws the metalic-hex plate texture.
![hexBase](https://github.com/TheCricket/Chisel-2/blob/master/src/main/resources/assets/chisel/textures/blocks/hexPlating/hexBase.png)
2. Sets the brightness to maximum, and then draws the colorized texture OVER the base.
![hexOverlay](https://github.com/TheCricket/Chisel-2/blob/master/src/main/resources/assets/chisel/textures/blocks/hexPlating/hexOverlay.png)

Carpenter's blocks only appears to be using their own renderer... chich is problematic, as it's missing the second step.

**Comment by JadeCreeper** [comment]
Maybe the base should have a non-glowing version of those lines, thats would be a quick fix for facades.

**Comment by CptSpaceToaster** [comment]
Maybe?  Light wouldn't effect the base texture, and it might be harder to draw solid pixels on top of solid pixels...  

This would also require 16 different versions of the base texture which clutters up our end... when it's not necessary... this sounds more like carpenter blocks' problem for not using our renderer... unless we didn't set something up properly, which I doubt at this moment.

**Comment by JadeCreeper** [comment]
Well at least it would fix facades.

**Comment by tterrag1098** [comment]
There would be no ill effects from filling in those pixels on the underlay.

**Comment by CptSpaceToaster** [comment]
The only "ill effect" if we can even call it that, would be the clutter on our end to choose decide which hex texture to use, as it's currently only using one base texture, and changing the color on top of it.

**Comment by tterrag1098** [comment]
I'm saying you could just fill in the blank pixels on the underlay with gray or something and that would be fine. No new textures needed.

**Comment by CptSpaceToaster** [comment]
Oh..... That works I guess.....

**Comment by tterrag1098** [comment]
What kind of facade? Working fine here: http://puu.sh/ejYtf.jpg

**Comment by JadeCreeper** [comment]
AE2 facades.

**Comment by Drullkus** [comment]
Which I unintentionally did with a recent commit, if that's what you're saying.

On Jan 09, 2015, at 07:58 PM, tterrag1098 <notifications@github.com> wrote:

I'm saying you could just fill in the blank pixels on the underlay with gray or something and that would be fine. No new textures needed.
—
Reply to this email directly or view it on GitHub.

=

**Comment by JadeCreeper** [comment]
You also cannot place beds or doors or anything similar on them.

**Comment by tterrag1098** [comment]
AE2 facades will never work with this kind of rendering. It's just not possible as they only can grab a single icon and render it.

**Comment by JadeCreeper** [comment]
But thats why having the color on the base would fix that.

**Comment by CptSpaceToaster** [comment]
not really, because the entire point of the hex blocks, was to have the color ignore the lightmap.  AE2 Facades can't handle that part...

**Comment by JadeCreeper** [comment]
There is still the problem of not being able to place beds, torches, doors, Etc. on the hex plating blocks.

**Comment by CptSpaceToaster** [comment]
<sarcasm>
Bug is intentional, Hex blocks are too cool to be covered by beds, torches, or doors.
</endSarcasm>

To answer, they must have some sort of issue when Minecraft checks if they are solid.  I'll look into what's going on there.  We'd want you to be able to make an entire base out of hex blocks if necessary.
