### ISSUE TITLE
Duplicate Blocks

### ISSUE THREAD

**Issue by warlordjones** [TheCricket/Chisel-2#123]
1. The descriptions for plank blocks of metadata 14 and 15 are the wrong way around in my opinion.
2. Meta values 6 and 7 are the same block for Cobblestone, Mossy Cobblestone and Limestone. Same description and texture. 
3. Diamond blocks 1 and 6 are VERY similar in texture.

**Comment by warlordjones** [comment]
Gah, can't label the issue

**Comment by warlordjones** [comment]
See #126

**Comment by tterrag1098** [comment]
Is this fixed by your PR?
