### ISSUE TITLE
Auto Chisel block - Dupe any item or block

### ISSUE THREAD

**Issue by smithnc07** [TheCricket/Chisel-2#125]
I've tested this with just Chisel 2 installed. 
Steps to reproduce:
1. Craft Auto Chisel Block and place it.
2. Right Click on block and put any valid block in the top left and bottom center slots. In this case I used cobblestone in both. 
3. Place what ever item you want to dupe in the top right slot. (nothing needs to be in the upgrade slots)
4. Watch the item in the top right increase. Doesn't seem to matter what it is, armor, blocks, ores, etc.

**Comment by warlordjones** [comment]
The Autochisel is completely broken in the currently released version of chisel, it has already been rewritten and fixed for the next version.

**Comment by tterrag1098** [comment]
The fact that he doesn't mention anything about needing a chisel (which I know for a fact the autochisel needs a chisel item in it to do *anything*) lets me know that he's not on a dev build :P
