### ISSUE TITLE
Slabs are forced into bottom-half of 1x1 space, even when placed in top-half.

### ISSUE THREAD

**Issue by Drakonas** [TheCricket/Chisel-2#127]
It seems this issue has been in place since the pull from the original mod's source.

Notes in the original mod's changelog show the author stating a slab problem being fixed, but it's a vague enough sentence to not know if the bug fixed was the bug I am reporting. (He states there is a bug with top-half placement AFTER stating a bug was fixed)

Changelog here. Look at 1.5.3 version notes. https://github.com/Pokefenn/Chisel/blob/master/changelog

Steps to reproduce: (In this example we'll use marble slabs)

(Note to author: Really wish you could simplify this by being able to craft already-chiseled blocks into stairs and such, instead of always having to make the stairs out of the raw block first and then chiseling them.)

(EDIT: No longer necessary. problem affects all chisel-mod slabs). Take a stack of marble (from Chisel mod), and use a 3x3 crafting grid to craft 30 of the marble blocks into 60 marble slabs.
(EDIT: No longer necessary. problem affects all chisel-mod slabs). Take the slabs, and chisel them to a pattern of choice.
1. Take a marble slab from the chisel mod, and attempt to place one of them in the top half of a block space with nothing present in the said space.

Expected result: slab is placed in the top-half section of the 1x1 space.

Actual result: slab is placed in bottom-half section of the 1x1 space.

**Comment by tterrag1098** [comment]
What version are you using?

**Comment by Drakonas** [comment]
Sorry. lol. It's the version in the latest 1.7 Direwolf20 pack: 2.1.3. I did some searching on the issue tracker and commits, and I don't see any details on this getting fixed, so I thought I'd make a new issue.

**Comment by CptSpaceToaster** [comment]
screenshots help!

**Comment by Drakonas** [comment]
I can do you one better: http://db.3rdn3rd.com/img/2015-01-10_20-12-27.gif
Update: This bug applies to all chisel-mod slabs, even naturally occuring blocks being turned directly into slabs.

**Comment by Drakonas** [comment]
Direwolf20 modpack listing for the current latest pack version (1.0.3) can be found here: https://feedthebeast.atlassian.net/wiki/display/PML/Direwolf20+%281.7.x%29+1.0.3

**Comment by VictiniX888** [comment]
Can confirm this happens with the latest commit.

**Comment by warlordjones** [comment]
As a side note, I'm looking to rework slabs and stairs. I've yet to discuss this with the rest of the team though.

**Comment by tterrag1098** [comment]
I agree with the cleanup, but this has been patched for now. Much cleaner (as clean as it can be).
