### ISSUE TITLE
Cannot place blocks in chisel after left clicking chisel in hotbar

### ISSUE THREAD

**Issue by skermajo** [TheCricket/Chisel-2#128]
v2.2.25.

Under this circumstance you are unable to place blocks inside the chisel:

1. Chisel in hotbar
2. Right-click to open chisel gui
3. Left click the chisel in your hotbar (with the chisel gui open)
4. You now cannot place blocks in the chisel (I was using spruce planks to test)

**Comment by VictiniX888** [comment]
Can confirm it still happens with the latest commit.

Additional info:  
- You can still shiftclick stuff into the slot, however, no variations appear, and it will not let you turn it into anything
- You can't get the stuff you put into the Chisel out of it anymore.
- If you close the Chisel GUI with stuff stuck in there, the stuff disappears when you reopen it.
