### ISSUE TITLE
Chisel 2 DEV 2.2.2.d8882fb [Multiple Bugs] [Dev version] [Minor]

### ISSUE THREAD

**Issue by SnowShock35** [TheCricket/Chisel-2#140]
Hi Chisel devs,

I have a couple of bugs to report so here they are...

Bug 1 - New colored sand making the wrong sound on place

Bug 2 - The new road ines have incorrect descriptions

![2015-01-13_17 21 16](https://cloud.githubusercontent.com/assets/8388680/5725195/b94c5846-9b48-11e4-85c0-813d19e33894.png)
![2015-01-13_17 21 15](https://cloud.githubusercontent.com/assets/8388680/5725196/b94defc6-9b48-11e4-959c-70343a4afcff.png)
![2015-01-13_17 21 13](https://cloud.githubusercontent.com/assets/8388680/5725197/b94f99c0-9b48-11e4-9f6e-080a71c32c32.png)

**Comment by tterrag1098** [comment]
Road lines have been fixed. I'll see about the other one.

**Comment by SnowShock35** [comment]
Ok thanks ;)

**Comment by BBoldt** [comment]
Adding on to this one, all of the sand recipes have the wrong color dyes in them:


![](http://i.imgur.com/KfYzB1l.png)
![](http://i.imgur.com/rybXpbG.png)

**Comment by MasterArt** [comment]
were did you get the jenkins builds?

**Comment by CptSpaceToaster** [comment]
From our Jenkins build server: http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/

**Comment by tterrag1098** [comment]
Although funnily enough the "dev" builds are probably more stable than the latest "real" build at this point :P

**Comment by Drullkus** [comment]
Shots fired? Idk :p

**Comment by tterrag1098** [comment]
Colored sand went poof.
