### ISSUE TITLE
Chisels on Autochisel render as a regular particle when in Fast rendering

### ISSUE THREAD

**Issue by Drullkus** [TheCricket/Chisel-2#144]
![2015-01-14_20 23 28](https://cloud.githubusercontent.com/assets/5010174/5752498/7199e138-9c2b-11e4-877d-6ffe068c606e.png)

**Comment by Drullkus** [comment]
Oooh, issue number 144.

12^2 :D

**Comment by CptSpaceToaster** [comment]
Feature?

**Comment by Drullkus** [comment]
Well, it renders as a particle on the Auto Chisel. You might wanna play with it while you're on fast render instead of fancy render

By particle I meant it faces you no matter what direction -- this picture does no justice :(

**Comment by CptSpaceToaster** [comment]
Feature?

**Comment by Drullkus** [comment]
But it looks weird? :(

**Comment by tterrag1098** [comment]
Fixed, albeit with quite the hack.
