### ISSUE TITLE
Idea in the future: Chiselable Common Modded Blocks

### ISSUE THREAD

**Issue by Drullkus** [TheCricket/Chisel-2#145]
> Ok, so 'common' I mean like 5 mods that add a copper or a tin block.

I'm thinking we should in the future, maybe after 2.3.0, we should implement enchiselment of common modded blocks. You can chisel one copper block into another copper block. Just an idea.

The problem is, some mods like Thermal Foundation (I think) don't oreDict their friggin' blocks so I can't turn one metal block into another. We might have to do some tricky stuff to go around this

**Comment by BBoldt** [comment]
Makes sense, metal blocks like that are pretty much a decorative item.

Since you have so many slots now you could even do fancy textured versions like there are for iron or gold.

**Comment by Drullkus** [comment]
That will come as well :)

**Comment by warlordjones** [comment]
I'd also had this planned. Copper/Tin are definite, but it shouldn't be too hard to add other slightly less common metals. However, this raises the issue of which mod to base our textures off. My idea to work around this is varieties for each existing texture of metal block, from the various mods, which are all loaded whenever any metal block of that type is loaded. I'm not sure I explained that well.

**Comment by Drullkus** [comment]
Er this is done. Not sure why not closed
