### ISSUE TITLE
Chisel2_DEV-2.2.2.297a09c Dupe Bug

### ISSUE THREAD

**Issue by Kolatra** [TheCricket/Chisel-2#146]
I have tested this with both variants of the chisel item. Placing an item in the first slot in the player's inventory and shift-clicking it moves it to the next slot, and doubles the amount currently there. This is on the latest version on the jenkins server.
![2015-01-15_01 18 19](https://cloud.githubusercontent.com/assets/3821892/5754321/8f956d3c-9c54-11e4-85ed-46a129b5c91e.png)
![2015-01-15_01 18 25](https://cloud.githubusercontent.com/assets/3821892/5754322/9299c80c-9c54-11e4-9c86-524f33f43c45.png)

**Comment by tterrag1098** [comment]
Already found and fixed. Thanks for the report though.
