### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by tterrag1098** [TheCricket/Chisel-2#147]
ICarvable kinda...sucks. It only passes the metadata, no world reference or coordinates. It would make addons much more possible if this interface could be changed, but of course this means breaking any mods that use it at this point. Does anyone else on the team know of any? If not, we could probably change this without much info (since the next version is 2.3.0 anyways).

**Comment by Choonster** [comment]
[ChiselFacades](https://github.com/Choonster/ChiselFacades) uses ICarvable to detect which metadata values of each block are valid variations so I know which values to register as Facades. I don't mind if the API changes.

Ideally, I'd like a way to get all valid metadata values for any given block. It looks like ICarvingGroup may be able to do this.

**Comment by tterrag1098** [comment]
@Choonster That should be quite easy with the new Carving stuff. You can get a group from the Carving registry and do what you want with that. Thanks for you input.

**Comment by Drullkus** [comment]
I am in favor of the refactor. I think it's essential we do this if we want to make addons easier to make and encourage them as well. I heard that Tehnut is already making a RF chisel... Niiiiiice.

**Comment by tterrag1098** [comment]
Implemented. Feel free to look over the changes @Choonster

**Comment by Choonster** [comment]
I forgot to respond to this earlier, but I ended up using the ICarvingGroup API and it worked pretty well (I just had to ignore any non-Chisel blocks in the group).

ChiselFacades was made mostly obsolete by a recent BuildCraft commit, so this doesn't matter as much any more.
