### ISSUE TITLE
DEV-2.2.2.0d0f73d - Auto Chisel Loses Contents when mined with pickaxe

### ISSUE THREAD

**Issue by dirtyfargo** [TheCricket/Chisel-2#148]
When I mine the Auto-Chisel with a pick-axe, I lose the chisel that was inside and the upgrades. Not sure if this is already known or not so apologies if so :) 19 second unlisted video demonstration below if needed
http://youtu.be/x2fHxHekwKg

**Comment by Drullkus** [comment]
At least it's not the other kind of dropping incorrectly... :P 

Context: In 1.2.5, if you broke any Tubestuff blocks with a block breaker, the inventory will both drop from the block itself AND drop from the back of the Block Breaker -- Resulting in an item duplication
