### ISSUE TITLE
Chisel and Auto-Chisel Break After One Use

### ISSUE THREAD

**Issue by Kolatra** [TheCricket/Chisel-2#150]
With the config setting allowChiselDamage=true, left clicking with both variants break it instantly. I don't know if this is intentional or not.

**Comment by CptSpaceToaster** [comment]
This is not intentional.

**Comment by tterrag1098** [comment]
This is not reproducible and you have not given much information. What version? What exactly were you doing?

**Comment by Kolatra** [comment]
Using Chisel2_DEV-2.2.2.297a09c.

I left clicked on a Stone block in the world with a Chisel.
![2015-01-17_00 22 42](https://cloud.githubusercontent.com/assets/3821892/5788069/11648f88-9ddf-11e4-8409-5e86d1a85618.png)
![2015-01-17_00 22 44](https://cloud.githubusercontent.com/assets/3821892/5788070/16cad27a-9ddf-11e4-9d67-f490f10ab610.png)

**Comment by Yucca86** [comment]
Do you mean allowChiselDamage=false? I had this instabreak of chisel in my server with Chisel2-2.2.2.25 with the config set to false. If I allowed damage to chisel, it would work just fine.

**Comment by Kolatra** [comment]
I just noticed the typo, yes, it is set to false.
