### ISSUE TITLE
[Auto Chisel] Using Stack Upgrade causes chisel's damage to only go up by one

### ISSUE THREAD

**Issue by VictiniX888** [TheCricket/Chisel-2#158]
For every stack of stuff chiseled.
Is this intentional?

Chisel version: commit b8eaaca678a46247382e9203a75244836193fe09
Forge version: 1286

**Comment by tterrag1098** [comment]
Yeah that's how it should work. Chisel is only supposed to take damage once per operation. It works the same in the hand.
