### ISSUE TITLE
Finish up Diorite, Andesite, and Granite

### ISSUE THREAD

**Issue by BBoldt** [TheCricket/Chisel-2#159]
* Granite and Diorite have 32x textures for some reason
* Add in the vanilla recipes for those blocks
* Noticed some chisel variations in the texture folder that don't seem to be blocks yet

http://minecraft.gamepedia.com/Diorite
http://minecraft.gamepedia.com/Andesite
http://minecraft.gamepedia.com/Granite

**Comment by tterrag1098** [comment]
I agree that the texture on them is bad...but I don't think it would be kosher to straight up steal mojang textures. Suggestions?

**Comment by BBoldt** [comment]
Well the current texture is just the mojang one tiled 4 times.

@Drullkus, Maybe you could design some original textures for these 3 stone types that look similar to the mojang ones without being a direct ripoff.

**Comment by tterrag1098** [comment]
I know it is :L

**Comment by ate0ate** [comment]
I don't know if its that bad to use the mojang texture really, I mean the whole concept is basically straight porting a 1.8 feature into 1.7.10. Vazkii already adds mojang prismarine into 1.7.10 worlds in Botania and I've never heard anyone make the claim of "stealing" the texture or idea that I'm aware of.

**Comment by Drullkus** [comment]
To be honest, I would actually use Mojang textures for a straight port-down like this. With 16, though... Not 32.

**Comment by tterrag1098** [comment]
This should be implemented now.
