### ISSUE TITLE
Railcraft Quarried Stone has issues with chisel

### ISSUE THREAD

**Issue by BBoldt** [TheCricket/Chisel-2#160]
Currently doesn't seem to be chiselable like the other railcraft blocks either.

Using Chisel2_DEV-2.2.2.462edc2.jar.

Related issue: https://github.com/TheCricket/Chisel-2/issues/49

**Comment by BBoldt** [comment]
Also I think abyssal should be grouped in with basalt, as it's basically the same thing.

**Comment by warlordjones** [comment]
But does quarried stone = marble?

**Comment by tterrag1098** [comment]
I disagree, I don't think quarried stone should be transferrable to marble.

**Comment by BBoldt** [comment]
@tterrag1098 

After some more thought about it, I agree with you. It's *VERY* similar, but I guess it is different enough to be considered it's own block type.
Also, considering the way railcraft decorative blocks are treated in chisel now, it would make more sense. 

Main reason I was pushing for this is because I don't want to be forced to generate 2 different nearly identical types of white stone in a world. 

Going to leave this issue open as Quarried stone doesn't seem to be chiselable like the other railcraft blocks.

**Comment by primetoxinz** [comment]
you have to use the already processed ones, not just the direct stone

**Comment by BBoldt** [comment]
Welp, guess this issue is closed then.
