### ISSUE TITLE
Weird blocks in Group from Geostrata

### ISSUE THREAD

**Issue by Voidi** [TheCricket/Chisel-2#161]
I have Geostrata V3b and Chisel 2.2.1 installed.
When i put Limestone/Marble (whatever from which mod) in the Chisel
i become Redstone/Glowstone bricks from Geostrata (they work as input for the Limestone/Marble variation).
Is this intentional or a bug?

**Comment by CptSpaceToaster** [comment]
This sounds like it's an odd issue with how Geostrata registered it's blocks in the Ore Dictionary.  It doesn't sounds quite right, but it doesn't sounds like Chisel is the root cause of the problem here.  I'll leave this "un-labeled" until someone who knows more about Geostrata can read this.

**Comment by tterrag1098** [comment]
@ReikaKalseki Do you know why this would happen? Oredict issues or...?

**Comment by Voidi** [comment]
I assume that here https://github.com/TheCricket/Chisel-2/blob/dd6b4aed8807b3c72d19dc1e0cc778ce4a0a9526/src/main/java/com/cricketcraft/chisel/compat/MarbleCompatibility.java#L140 were the wrong blocks are selected.
But since this file is gone, and in the build i compiled from latest commit, everything seems ok, this can be closed.

**Comment by CptSpaceToaster** [comment]
... Yes... yes it can :)

**Comment by ReikaKalseki** [comment]
The new code is still wrong. I will write an API hook for you.

**Comment by ReikaKalseki** [comment]
Done.
https://github.com/ReikaKalseki/GeoStrata/blob/master/API/RockGetter.java

**Comment by Voidi** [comment]
Oh Nice! Some hugs for you @ReikaKalseki

**Comment by CptSpaceToaster** [comment]
:+1:
