### ISSUE TITLE
[Chisel] Crash when left clicking with Panel Mode?

### ISSUE THREAD

**Issue by VictiniX888** [TheCricket/Chisel-2#162]
I was just spamming leftclick with Panel Mode on the Iron Chisel, and it crashed (probably around the same time the Chisel was supposed to run out of durability)

http://pastebin.com/wTjCs0f1

Chisel version: Dev Build 14
Forge version: 1286

EDIT: Seems to happen only when the Chisel is *supposed* to chisel more items (eg Panel Mode), but doesn't have enough durability left.

**Comment by tterrag1098** [comment]
Yep that's exactly it. Easy fix.
