### ISSUE TITLE
Crash at startup using latest official release (2.3) from curseforge.

### ISSUE THREAD

**Issue by ate0ate** [TheCricket/Chisel-2#165]
I was going to test out the new official release to see if the world generation issues I reported in issue #130 were fixed yet and I seem to just crash at startup.

I'm using forge 1286 and no other mods at all besides chisel 2 with a completely fresh minecraft 1.7.10 instance.

http://pastebin.com/GhZeHK7d

**Comment by Choonster** [comment]
Cricket just uploaded 2.3.1, which fixes this issue.

**Comment by ate0ate** [comment]
Nice, thanks!
