### ISSUE TITLE
Feature Request: Blocks Emitting Light

### ISSUE THREAD

**Issue by nerdnosyd** [TheCricket/Chisel-2#166]
I would absolutely love to have some sort of mechanic that lets specified chisel blocks emit light (especially some of the new ones like the hex plating)

Perhaps expending glowstone within the (new and awesome) Chisel UI itself to make blocks emit light or a new item/machine.

**Comment by tterrag1098** [comment]
Not sure this kind of thing really belongs in Chisel. However, there is such functionality in [EnderIO](http://enderio.com) where you can paint glowstone as other blocks. This works with chisel blocks (even connected textures!).
