### ISSUE TITLE
Sapling Conversion

### ISSUE THREAD

**Issue by soundlogic2236** [TheCricket/Chisel-2#171]
I like the variant leaves added, but would like a config option so that I can get them without permitting the implicit conversion of one sapling to another (via leaf conversion)

**Comment by warlordjones** [comment]
Pardon?

**Comment by soundlogic2236** [comment]
As in, if one can convert leaves, that is implicitly permitting converting saplings. Even in a world with only oak saplings, one could then get a spruce sapling. Because leaves drop saplings.

**Comment by CptSpaceToaster** [comment]
so... you want oak leaves to only be chisel-able to oak varients... which would exclude users from chiseling 200 oak leaves into 200 birch leaves, which then allows them to get birch... am I correct?

**Comment by tterrag1098** [comment]
Fixed with a config to turn it off. Default behavior is that you can ONLY chisel to the chisel variants, and not back.
