### ISSUE TITLE
Invisible Blocks with Optifine

### ISSUE THREAD

**Issue by GRANITsalvo** [TheCricket/Chisel-2#173]
Problem: All Chisel blocks are invisible/not rendering when paired with Optifine Ultra.
Minecraft 1.7.10
Forge 1.7.10-1.1.0.314-universal
Chisel versions 2.3.1 - 2.3.3.28
Optifine 1.7.10 HD Ultra B4

Troubleshot the two grouped with other mods and paired alone.  Optifine 1.7.10 Lite A4 would also crash when loading the world when paired with Chisel.

Solution:  Oddly enough, Optifine 1.7.10 HD Standard B4 works just fine. So this is more to assist anyone googling a similar problem.  

Let me know how I can provide more useful information if you need it.  I am a novice at minecraft.

**Comment by CptSpaceToaster** [comment]
This might be a graphics card specific problem.  We'd need someone else to confirm.

**Comment by HanFox** [comment]
That doesn't appear to be a Forge version. It looks like a ForgeMultiPart version ;)

Certain versions of Forge are incompatible with certain versions of Optifine (or vice versa if you will). Other mods have had issues with disappearing blocks.

Have you tried Optifine Ultra B4 with the "compatible" version it states which is Forge 10.13.2.1240?

**Comment by TheCricket** [comment]
We will not fix chisel blocks being invisible with optifine, it is their bug. We render for vanilla not optifine

**Comment by GRANITsalvo** [comment]
Wow, that was quick. Thanks.  I did not notice the compatable B4, but I will look again.  It could easily be a few things, but I am not experienced with java workings.   What I did notice was that all google troubleshooting efforts on a novice level led me back here.  TheCricket; I did not expect you to make it work with Optifine, but I noticed a problem AND a solution, I figured others could benefit from this.  Did not mean to offend.

**Comment by sysrover** [comment]
This problem start when you use multi-core chank loading. This options only on Optifine Ultra. Thats why on standart you have no problem.
But multi-core setting give bigger performance.

**Comment by bobbygoin** [comment]
Yeah, Optifine boosting performance and adding nice features sure is "peasantry". And then leaving users who love your mod but don't have computers nice enough to run the game at good framerates and NEED optifine to make it playable can go fuck themselves, right? Fuck you.

**Comment by EchoBounce** [comment]
wow, someone is salty over not being able to afford a nice pc
