### ISSUE TITLE
Connected texture problem Laboratory Blocks

### ISSUE THREAD

**Issue by malice936** [TheCricket/Chisel-2#175]
https://drive.google.com/file/d/0B92V_sU6-f-hdG1Mbml4UkhfQ0E/view?usp=sharing

Screenshot above showing version Chisel2_DEV-2.2.2.0d0f73d

**Comment by Drullkus** [comment]
How can we reproduce this issue?

**Comment by tterrag1098** [comment]
Please udpate your version, that one is quite out of date. Not saying it will fix the issue but I would like to check.

**Comment by tterrag1098** [comment]
Actually, I found the bug.
