### ISSUE TITLE
Bed issue

### ISSUE THREAD

**Issue by hron84** [TheCricket/Chisel-2#179]
If you right click on the bed with an iron chisel to sleep, it activates its GUI before activating sleeping animation. It would be good if chisel can skip opening its GUI in this specific case.

Chisel version: 2.3.3.28 (I downloaded latest version from curse.com)

**Comment by Aedaeum** [comment]
They just released a new version, you should check if you're still having this issue with v2.3.5

**Comment by tterrag1098** [comment]
It won't.

**Comment by hron84** [comment]
I will definitely check that out, thanks

**Comment by tterrag1098** [comment]
Duplicate of #119
