### ISSUE TITLE
Ice Pillar textures lack transparency

### ISSUE THREAD

**Issue by HanFox** [TheCricket/Chisel-2#189]
1) You can see through ice pillars to gaps below (i.e. x-ray).

2) The recipe for the ice pillar creates the pillar with metadata :1 instead of, like most other blocks, making the one with metadata :0. Took me a little while to even realize they had recipes due to that.

3) Also, a lot of the textures are lacking transparency. I'm guessing they're all meant to be transparent not just carved-side.png and the *-top.png's.

4) All the packed icepillars are missing their localized description text.

**Comment by TheCricket** [comment]
2) if you update to the latest version it shows all of the variants for a block in NEI and which one you need to craft, its highlighted in orange.

**Comment by HanFox** [comment]
Using Chisel2_DEV-2.3.5.7f88e05.jar from the colorlights Jenkins (i.e. the latest build) the orange box highlights which is the active block (i.e. the block you have clicked "Show Recipes" on), not which one is the one to craft in order to be able to access the chisel variants.

**Comment by HanFox** [comment]
So the above commit fixes 1, 2 and 4.

However now packed icepillars and normal icepillars have no discernible difference. From looking at other blocks packed ice is not meant to be transparent whereas normal ice is. However, as it currently stands both are just obeying whatever transparency is set in the .png.

**Comment by tterrag1098** [comment]
Hrm, true. I'm also not an artist so I won't be fixing 3. And if you're looking for a 5th issue, ice stairs place the completely wrong blocks.

**Comment by HanFox** [comment]
Above commit fixes 3). Now all that's left is tterrag1098 pointing out 5) ice stairs (and other stairs) placing wrong block :P

**Comment by tterrag1098** [comment]
5) fixed

3) @Drullkus

**Comment by Drullkus** [comment]
Oh hai

Oh... Transparent textures... Can do later

**Comment by warlordjones** [comment]
No need. They are all transparent already, and I use the same textures for packed ice, just with alpha disabled.

**Comment by tterrag1098** [comment]
Um...no they aren't. Go look ingame.
