### ISSUE TITLE
Technical Transparent Malfunctioning Fan doesn't have its own texture

### ISSUE THREAD

**Issue by HanFox** [TheCricket/Chisel-2#191]
That particularly block is just using the StillTransparent texture for the face and while yes, a non-moving fan could be malfunctioning it's not quite the same as the opaque one with all the sparking.

**Comment by Drullkus** [comment]
Oops... I don't think I have quite gotten around to doing that... XD

**Comment by Drullkus** [comment]
Yeah. I've got a complex animation under progress. 

The animation file will get massive though... :(

**Comment by Drullkus** [comment]
I've done some of the things, I need to do the other things for this tex

**Comment by HanFox** [comment]
Any progress? 2 months and a random massive fan later and this texture is still "broken".

**Comment by Drullkus** [comment]
I've got my hands on so many projects! ;-;

**Comment by Drullkus** [comment]
Ok I tried tackling it today. Without the alpha channel the texture will be horrendous. :\

I'm just gonna make it a slow fan and be done with it.
