### ISSUE TITLE
Crash due to NullPointerException

### ISSUE THREAD

**Issue by BB20101997** [TheCricket/Chisel-2#194]
When joining my Server running Material Energy^4 Modpack
the game chrashes with the following Error:
[Pastbin](http://pastebin.com/6CcmLntv)

The NullPointerException happens at com.cricketcraft.chisel.client.render.RenderBlocksColumn.connected(RenderBlocksColumn.java:19)

**Comment by tterrag1098** [comment]
This is already fixed, will be released soon. Fix can be gotten from the dev builds.
