### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Notchinus** [TheCricket/Chisel-2#201]
Was playing on the Material Energy^4 modpack version 1.03, only mod I added was FastCraft.
Forge version is whatever is used on FTB Launcher.
Crash Report:
http://pastebin.com/PfBqZgMT

I was in the Ice Palace spatial IO, used a Tinker's Hammer with silk touch to break some of the blocks when the game crashed.  Updated to the latest public chisel relase (2.3.5.31) and rebooted, game loaded but crashed when accessing inventory.  Updated to latest dev release (2.3.5.0064), same result.

**Comment by TheCricket** [comment]
Should be an easy fix

**Comment by TheCricket** [comment]
Unable to reproduce in the github version
