### ISSUE TITLE
Disabling jackolantern [and maybe others] causes the client to crash when the tab with the jackolantern icon is loaded

### ISSUE THREAD

**Issue by Nentify** [TheCricket/Chisel-2#202]
`B:jackolantern=false` causes the client to crash [http://pastebin.com/cBbuz3NJ] when the tab in the creative inventory is navigated to, immediately as you press the next page button.

**Comment by TheCricket** [comment]
It will crash the others as well

**Comment by Nentify** [comment]
I assumed as much

**Comment by TheCricket** [comment]
I think I will just add static tab icons that you can't disable

**Comment by TheCricket** [comment]
my b on the close lol
