### ISSUE TITLE
Underground Biomes Constructs integration

### ISSUE THREAD

**Issue by T145** [TheCricket/Chisel-2#206]
Chisel 2 causes a fatal world error when booted w/ UBC since the mod removes cobblestone. Making those blocks optional or ore dict compatible should at least resolve that.

**Comment by tterrag1098** [comment]
They are optional, just disable the cobblestone feature.

**Comment by T145** [comment]
Sure, I know that, but wouldn't it be better to have additional compatibility for it so that doesn't have to be done manually?

**Comment by TheCricket** [comment]
We can't really test if a mod removes a block, it's up to the pack maker to fix that, hence why everything in chisel is pretty much configurable
