### ISSUE TITLE
Crash at startup using jenkins dev build 2.3.5.0431b9e (missing malfunctioning fan texture?)

### ISSUE THREAD

**Issue by ate0ate** [TheCricket/Chisel-2#208]
Crash at startup after updating to latest dev build. looks related to commit ed3e85f1a5fa89b9725c51416d32dd0ad06c8ef2

http://pastebin.com/MqME8zLM

**Comment by TheCricket** [comment]
Not a crash just a missing texture, it keeps chisel from loading so we dont release anything with broken textures
