### ISSUE TITLE
We need to figure this out...

### ISSUE THREAD

**Issue by Drullkus** [TheCricket/Chisel-2#211]
Take a gooooood look at the picture.

![2015-02-06_22 10 45](https://cloud.githubusercontent.com/assets/5010174/6091056/028716ba-ae4d-11e4-8499-60270dadac35.png)

**Comment by xeronut** [comment]
Not gunna lie.. I see tessellating manjunk on those bricks.  Easier to see on the far right brick wall.

I'm sorry.

**Comment by CptSpaceToaster** [comment]
?

**Comment by Drullkus** [comment]
the blocks were tiling backwards on two sides of the block. With a little logic I put in a simple fix.
