### ISSUE TITLE
[2.3.5.31] ProjectRedExploration Marble Bricks do not chisel.

### ISSUE THREAD

**Issue by frozenLake** [TheCricket/Chisel-2#214]
Hey, I loaded FTB Infinity, and started building a house out of Marble, to learn to my dismay that the Marble Bricks added by Project Red Exploration did not fit with Chisel's Marble Texture, so I tried to convert those bricks into the proper kind, to learn that the Chisel did not accept them.

I find that somewhat weird, as the standard marble works fine, so I looked through the code of both Chisel and Project Red, and in the compatability of Chisel2, learned that while "stonemarble" is supported, "brickmarble" is not.

**Comment by tterrag1098** [comment]
What is the recipe for marble bricks? And what is their metadata?

**Comment by frozenLake** [comment]
The recipe is 4 marble in a square shape, giving 4 bricks, and the ID in FTB Infinity is 2268:1, which considering the [placement in the project red code](https://github.com/MrTJP/ProjectRed/blob/3366dcd93358c84585a1fa01b4093af7a68f7f05/src/mrtjp/projectred/exploration/blocks.scala#L168), makes a small deal of sense.
