### ISSUE TITLE
[2.3.5.31] Scorching blocks missing

### ISSUE THREAD

**Issue by skzskormz** [TheCricket/Chisel-2#217]
Scorching blocks are missing, no documented change in the official change log file.

**Comment by CptSpaceToaster** [comment]
Define missing: Textures MIA?  Or the block doesn't even show up in your creative menu where it normally would?

**Comment by tterrag1098** [comment]
Scorching blocks were never finished AFAIK. They were removed because of
this and there are no plans to finish them. It would be up to our texture
artist (@Drullkus) to decide to add them back in.

**Comment by CptSpaceToaster** [comment]
@tterrag1098 It looks like they made it out into a release though... so we might have to look into this a bit more.

**Comment by skzskormz** [comment]
It surely was on the version i been using, 2.2.1, reason why I noticed their removal.

**Comment by tterrag1098** [comment]
Regardless, they were unfinished. Adding them back now wouldn't solve any
problems. As I said, it's up to @Drullkus

**Comment by Drullkus** [comment]
I'm not going to focus on that for now

**Comment by HanFox** [comment]
Even if they were unfinished from your point of view evidently people (as proven by this thread) still wanted them.

If they made it to a stable (and quite possibly were in people's builds) leave them in. Don't just tear them out. Even if they had no recipes (I honestly don't recall) people might want to MineTweaker them in.

Wasted a few hours texturing them for PureBDcraft now with no guarantee they'll be back.

**Comment by Drullkus** [comment]
I'm having the idea of re-adding them in the future as a subgroup of the lava blocks instead of crafting new blocks whole

**Comment by skzskormz** [comment]
Ill be waiting for that update, they where pretty awesome :+1:, was using in a meteor crash building and I logged in after the update to realize the place was dried up haha. Closing the thread anyway, i think this has been sorted out.

**Comment by tterrag1098** [comment]
@HanFox I realize this, but at this point it's spilt milk as there have been 4 releases since with them removed. Adding them back now would not recover the worlds.

**Comment by skzskormz** [comment]
No worlds been broken, not a single drop of milk wasted, just missing blocks, nothing that laying down the work again wouldnt fix the situation for me.
