### ISSUE TITLE
Tessellator crash - chisel cobble

### ISSUE THREAD

**Issue by Slind14** [TheCricket/Chisel-2#219]
Hey,

the referenced issue at minecraft forge contains all the information I have. The only thing it doesn't contain is that it changed once the chisel cobble was removed. 
https://github.com/MinecraftForge/MinecraftForge/issues/1698

In regards of Immibis respond, is chisel 2 probably doing anything like this? 
https://github.com/MinecraftForge/MinecraftForge/issues/981#issuecomment-61396617

**Comment by tterrag1098** [comment]
Duplicate of #200 as far as I can tell.
