### ISSUE TITLE
Colored chests

### ISSUE THREAD

**Issue by SHIuSH** [TheCricket/Chisel-2#220]
If you place anything in colored chest from chisel 2 in some time everything disappear from it

**Comment by TheCricket** [comment]
I said this a long time ago, we have been working hard on this.

**Comment by Gurakai** [comment]
all i can say... i wish i knew this before i lost alot of awesome loot i found whilst traveling about :/
this is a bad bug D: at least you working on it :3

**Comment by Gurakai** [comment]
oh, btw just wondering, would it be possible to like add a warning on the main forum page? like with all the explanations until the bug is fixed? would be nice for any other unsuspecting victims.

**Comment by tterrag1098** [comment]
This is fixed in latest release
