### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to com.cricketcraft.chisel.block.BlockPresent

### ISSUE THREAD

**Issue by the-ible** [TheCricket/Chisel-2#223]
Minecraft 1.7.10
Cauldron Server

I am personally unable to reproduce this bug, but a specific player on the bug can reproduce the problem reliably. His name is wesleytech.

First crash log from wesleytech
http://pastebin.com/ErwZSaXB

Most recent crash log from wesleytech
http://pastebin.com/7AiX0Xbb

I've examined the air block on the server. It's an air block, there is nothing present at that location.
Just to be sure I used the delete block plugin to delete whatever could possibly be at those coordinates. Still wesleytech continues to have these crashes.

**Comment by tterrag1098** [comment]
Presents are broken in current release. Tell him to stop using them. If you must have fixed presents you can use the dev builds.

**Comment by the-ible** [comment]
There is not a present at the specified location in the crash log. It is a block of air.
There is no present.

**Comment by Drullkus** [comment]
Oops, I broke Chiselable Air kappa

**Comment by tterrag1098** [comment]
There is a present somewhere, it might be adjacent to the given block.

**Comment by tterrag1098** [comment]
This crash can only come from present code

**Comment by CptSpaceToaster** [comment]
man... I wonder when Chisel is going to release those present blocks they keep talking about?  I bet they are really great!

**Comment by the-ible** [comment]
There was a Chisel present box about 5 blocks away.
I have destroyed the present box and hope this resolves wesleytech's crash issue.

**Comment by tterrag1098** [comment]
It will :P

**Comment by CptSpaceToaster** [comment]
unless..... 2 present boxes...
