### ISSUE TITLE
Massive FPS drop when Grimstone is on screen

### ISSUE THREAD

**Issue by freyskol** [TheCricket/Chisel-2#224]
Title.

System Specs:
Windows 7 Ultimate 64-bit
6GB RAM
Radeon HD 6670
AMD Athlon 2 X3 425 2.7ghz

This is using all grimstone variants as well as with carpenters blocks.

**Comment by CptSpaceToaster** [comment]
What version of Chisel-2 are you using?

When you press F3, does the listed FPS feedback reflect what you experience?
If "Yes"
1.) Load ONLY Chisel-2 and Forge
2.) Create a new world, in creative
3.) Take a screenshot with the F3 diagnostic menu open, displaying framerate.
4.) Place a suitable amount of Grimstone until the FPS drops is "massive"
5.) Take another screenshot

**Comment by freyskol** [comment]
My apologies for wasting your time. It was another mods problem that has now been solved. Confirmed Grimstone does not cause lag.

**Comment by CptSpaceToaster** [comment]
no problem
