### ISSUE TITLE
Marble Stairs exhibiting odd behavior

### ISSUE THREAD

**Issue by AkimboEG** [TheCricket/Chisel-2#235]
Marble stairs are exhibiting odd behavior. Trying to place some chiseled variant in the world will instead place another variant. These are sometimes extra buggy and can not be broken with pickaxes or chiseled into other variants, in-world and/or in chisel GUI.

1. Craft Raw Marble Stairs (from Raw Marble blocks)
2. Use chisel GUI to create Carved Marble Stairs (first variant after Raw Marble Stairs)
3. Place in world. Actual block placed is Raw Marble Stairs. Placed blocks can not be left-click chiseled and do not seem to break by pickaxe.

Tested with Chisel2-2.3.7.34.jar and forge-1.7.10-10.13.2.1291-universal.jar

**Comment by alexschrod** [comment]
There's still a strange behavior, at least in build 65. I first tried the latest, 71, but it caused my client to crash, so I went back to the earliest with this issue fixed.

Placing them down has been fixed, which is good, but left-clicking them with the chisel is still bugged. For me, it ONLY works on stairs "facing" east, and having a regular stair configuration (as opposed to upside-down stair configuration).

**Comment by alexschrod** [comment]
I discovered another, probably related thing. If you place down a stair that has metadata :8 when chiseled, such as the Dark Creeper Marble Stairs, and then break it, a set of stairs with metadata :1 is dropped.

![image](https://cloud.githubusercontent.com/assets/767490/6432650/c934612e-c058-11e4-83c6-7c7375cf00dc.png)

In the case of the Dark Creeper Marble Stairs, that's a Raw Marble Stairs. However, the ones you normally craft have a metadata of :0. Thus, these metadata :1-stairs cannot be used in a chisel:

![image](https://cloud.githubusercontent.com/assets/767490/6432657/03d8ecdc-c059-11e4-9ffe-92e089873f17.png)

Placing them down and breaking them causes them to revert to their correct metadata value, i.e. :0.

**Comment by blufus** [comment]
A quick fix for this problem is to use a saw (eg. Forge Microblocks) on the chiseled blocks you want for the stairs in order to make them manually.

**Comment by mcgraj3** [comment]
I have to agree with blufus. I don't craft vanilla stairs anymore, using FMB pillars instead. The nice benefit with Microblocks is that should you want to repurpose them, they reassemble back into whole blocks in any crafting window. Very handy.
