### ISSUE TITLE
Crash when pressing number keys from the Chisel

### ISSUE THREAD

**Issue by Doty1154** [TheCricket/Chisel-2#236]
http://paste.ee/p/MRcRD
When i was pressing a number key, in the chiseling menu. It crashed.

**Comment by CptSpaceToaster** [comment]
mod attempts to move object from chisel inventory to hotbar... crashes

**Comment by Doty1154** [comment]
Okie thanks for looking into it, sorry i didn't provide a whole lot of info...It was Very late for me when posting this

**Comment by warlordjones** [comment]
Can't seem to reproduce the crash, but it does allow you to move the chisel inside of the chisel, deleting it...

**Comment by CptSpaceToaster** [comment]
Open chisel, hover over item in chisel, press a number key, on an open Item slot on your hotbar.
