### ISSUE TITLE
Chisel-2 slabs don't behave quite like vanilla slabs - No redstone stacking

### ISSUE THREAD

**Issue by CptSpaceToaster** [TheCricket/Chisel-2#237]
![see](http://i1212.photobucket.com/albums/cc446/sarge64641/2015-02-18_110256_zps6960de80.png)

We'll need to figure out why our slab implementation doesn't work exactly like vanilla.

**Comment by tterrag1098** [comment]
Likely hardcoded checks for BlockSlab or some such.

**Comment by CptSpaceToaster** [comment]
[BlockCarvableSlab](https://github.com/TheCricket/Chisel-2/blob/dev/src/main/java/com/cricketcraft/chisel/block/BlockCarvableSlab.java) implements BlockCarvable and not vanilla's BlockSlab.  From a quick look, I don't see why we can't extend Minecraft's class here...
