### ISSUE TITLE
Connected Textures don't connect to Ender IO conduit facades

### ISSUE THREAD

**Issue by michael-3-141** [TheCricket/Chisel-2#239]
I'm not sure if this is a bug or feature request, but I noticed conduit facades from ender io detect neighboring connected texture blocks and display the right texture, but the chisel blocks don't detect the facades as valid blocks to connect to, so they don't display the right texture. Here's a screenshot demonstrating the issue:
https://imgur.com/a/SI4qa

**Comment by TheCricket** [comment]
What version are you running

**Comment by michael-3-141** [comment]
Chisel 2.3.5.31
Ender IO 2.2.5.311

Sorry if this bug was fixed already, I should have updated to the latest version before posting it here.

**Comment by Drullkus** [comment]
Try running chisel 2.3.7 and see if it's fixed.

**Comment by michael-3-141** [comment]
Updating chisel and ender io fixed it. Thanks and sorry for wasting your
time

On Mon, Feb 23, 2015 at 10:18 AM, Drullkus <notifications@github.com> wrote:

> Try running chisel 2.3.7 and see if it's fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheCricket/Chisel-2/issues/239#issuecomment-75504047>.
>



-- 
מיכאל אלגאוי michael elgavi <michael.elgavi@gmail.com>
