### ISSUE TITLE
Disable Particles

### ISSUE THREAD

**Issue by dninemfive** [TheCricket/Chisel-2#240]
It would be nice to have a config option to disable particles from blocks. Could be implemented by allowing values above one for the 'I:particleTickrate' variable - I've tried this, and it resets to 1 every time. 
Building large holystone/grimstone structures looks terrible with the particles.

In the same vein, perhaps blocks could respect the vanilla particles setting in the 'Options' menu.

**Comment by 61352151511** [comment]
Temp work-around
```
particlesTickrate = config.get(category, "particleTickrate", 1, "Particle tick rate. Greater value = less particles.").getInt(1);
```
Set it to the maximum value of an integer (2,147,483,647)
