### ISSUE TITLE
ServerCrash

### ISSUE THREAD

**Issue by frank89722** [TheCricket/Chisel-2#241]
When I start server it crash
version:Chisel2_DEV-2.3.7.aa5d07b
crash report:http://pastebin.com/rrFX48hi

**Comment by TheCricket** [comment]
Wait for a newer dev build, the nightlies are not meant to be for regular use. Expect that they won't work perfectly.

**Comment by tterrag1098** [comment]
I just fixed this, try the latest dev build now. http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/63/

**Comment by frank89722** [comment]
It work!
Thank's your hard work :)
