### ISSUE TITLE
Clear glass optical bug

### ISSUE THREAD

**Issue by landlife** [TheCricket/Chisel-2#248]
After we updated to latest version of Chisel 2 - 2.3.7 we noticed that the clearglass becomes not so clear anymore when you look at it in certian angle 

![rh4jara](https://cloud.githubusercontent.com/assets/10908626/6370384/2686fab0-bcf0-11e4-9f5a-a2dcf75c70e3.png)

**Comment by tterrag1098** [comment]
Optifine? What other mods are installed?

**Comment by landlife** [comment]
its a long list but we dont have optifine installed and its not in our modpack download eitherhave
i have checked this issue with 5 dirfrent players before i opened this issue none of them have optifine installed eitherhave
We are realy in love with Chisel2 and we will keep using it :D its just some minor issue time to time 

but we have have these mods installed on our server 

adv-repulsion-systems-59.0.2
advanced-machines-59.0.2
AdvancedSolarPanel-1.7.10-3.5.1
appliedenergistics2-rv2-beta-8
Armourers-Workshop-1.7.10-0.27.2.65
BiblioCraft[v1.9.2][MC1.7.10]
BigReactors-0.4.1A2
BluePower-1.7.10-0.2.857-universal
Botania r1.5-163
ChickenChunks-1.7.10-1.3.4.17-universal
Chisel2-2.3.7.34
CodeChickenCore-1.7.10-1.0.4.35-universal
CoFHCore-[1.7.10]3.0.0B9-40
CoFHLib-[1.7.10]1.0.0B8-34
CompactSolars-1.7.10-4.4.39.315-universal
ComputerCraft1.7
EnderIO-1.7.10-2.2.8.349
EnderStorage-1.7.10-1.4.5.27-universal
extrautilities-1.2.1
Hats-4.0.1
HatStand-4.0.0
IC2NuclearControl-2.0.8c
iChunUtil-4.1.3
immibis-core-59.0.5
immibis-microblocks-59.0.4
industrialcraft-2-2.2.657-experimental
InventoryTweaks-1.59-dev-152
ironchest-1.7.10-6.0.62.742-universal
Jabba-1.2.1_1.7.10
magicalcrops-1.7.10_0.1
malisiscore-1.7.10-0.10.5
malisisdoors-1.7.10-1.4.3
Mantle-1.7.10-0.3.2
MobiusCore-1.2.3_1.7.10
neiaddons-mc1710-1.12.2.9
NEIPlugins-MC1.7.10-1.1.0.9-unofficial
NotEnoughItems-1.7.10-1.0.4.83-universal
OpenBlocks-1.7.10-1.3
OpenModsLib-1.7.10-0.6
Opis-1.2.3_1.7.10
PowerConverters-1.7.10-3.0.4.47
ProjectE-1.7.10-PE1.2.0
ProjectRed-1.7.10-4.5.12.64-Base
ProjectRed-1.7.10-4.5.12.64-Compat
ProjectRed-1.7.10-4.5.12.64-Integration
ProjectRed-1.7.10-4.5.12.64-Lighting
ProjectRed-1.7.10-4.5.12.64-Mechanical_beta
ProjectRed-1.7.10-4.5.12.64-World
QmunityLib-1.7.10-0.1.78-universal
Railcraft_1.7.10-9.4.0.0
TConstruct-1.7.10-1.8.2a (1)
Thaumcraft-1.7.10-4.2.3.5
thaumicenergistics-0.8.9.0b-rv2
ThaumicTinkerer-2.5-1.7.10-162
ThermalExpansion-[1.7.10]4.0.0B8-23
ThermalFoundation-[1.7.10]1.0.0RC1-13
tubestuff-59.0.3
WR-CBE-1.7.10-1.4.1.9-universal

**Comment by CptSpaceToaster** [comment]
Have you tried repeating the issue with chisel-e as a standalone mod?  It'd be nice to know if this is a chisel-2 issue, or a mod conflict...

**Comment by landlife** [comment]
curently im at work i will test this out when i am back home sorry for the delay

**Comment by warlordjones** [comment]
I can't reproduce this.

**Comment by landlife** [comment]
sorry for the late reply but it toke some time to test everything out the mod it conflicts with is TConstruct-1.7.10-1.8.2a when we removed this mod the issue was resolved sorry for wasting your time 

It was strange cus i found later out that it was only acting like that on certian spots on the map and saw the tc forge was close aswell as soon i removed this mod to test it was resolved

**Comment by bonii-xx** [comment]
I assume you got slimpeads somewhere nearby? Should be fixed next version.
