### ISSUE TITLE
Chisel-able Crystals?

### ISSUE THREAD

**Issue by jaredlll08** [TheCricket/Chisel-2#250]
Hey, hope im not bothering you, I just came across this mod, Fluxed-Crystals (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2298000-0-0-4a-fluxed-crystals-everything-changed-when-i)  and I noticed the textures were pretty bad... the texture artist must be pretty bad...
So I thought... how would you make these crystals pretty... and then it hit me!
get your texture artist... @Drullkus to make new texture for the mod! but instead of making a pull request...
Chisel-able Crystals!

I'm sure it is possible! and it shouldn't cause too much fps lag

**Comment by TheCricket** [comment]
...
