### ISSUE TITLE
Unbreakable chisel?

### ISSUE THREAD

**Issue by jaredlll08** [TheCricket/Chisel-2#251]
We all have that problem of our chisels breaking... so why not make a new material, Dalektanium!
It will NEVER break from use, the only way for it to break is when the player gets hit with a sonic chisel(new chisel that changes blocks at a distance) at which point it will crumb to dust.
Also a side request, when the dalektanium chisel is used, it should have a sound effect saying "EXTERMINATE"

Hope you like my ideas :)

**Comment by TheCricket** [comment]
...

**Comment by TehNut** [comment]
Shhhh http://i.imgur.com/sb0yNhR.png

**Comment by warlordjones** [comment]
Feel free to make this an addon, but it certainly doesn't fit in the base mod.
