### ISSUE TITLE
Half of the limestone stairs revert to the other half on placement

### ISSUE THREAD

**Issue by bshelden** [TheCricket/Chisel-2#253]
When placing limestone pairs, half of the available options 'reset' to the other half on placement.  Specifically, any stair with a metadata of 8 reverts to the same block id but with no metadata.

So <chisel:limestone_stairs.0:8> reverts to <chisel:limestone_stairs.0> when placed (Notation from minetweaker)

**Comment by bshelden** [comment]
This is likely a dupe of #235

**Comment by tterrag1098** [comment]
Yes, it is.
