### ISSUE TITLE
Connect Textures (North-South) Not Connecting Correctly - Still

### ISSUE THREAD

**Issue by chloeprince** [TheCricket/Chisel-2#254]
These still don't connect correctly. 

The blocks that run North & South are messed up. The ones that run East to West are fine. This is the case with all the laboratory blocks, and some other chisel connected textures.

Using:  Chisel2_DEV-2.3.7.71.jar

![2015-03-01_16 55 15](https://cloud.githubusercontent.com/assets/6889524/6433107/f6865332-c033-11e4-977a-fac1b9f395fc.png)

**Comment by Drullkus** [comment]
We're rewriting the CTM stuff at the moment, then we'll see.

**Comment by CptSpaceToaster** [comment]
... We are eh?

**Comment by Drullkus** [comment]
@CptSpaceToaster Now it's "We were rewriting the CTM stuff after you took the screenshots. :P"
