### ISSUE TITLE
Allow chisel pumpkins to apply to snow golems.

### ISSUE THREAD

**Issue by TimB1087** [TheCricket/Chisel-2#255]
I know it'll require some rewriting of the actual snow golem mob, but how awesome would it be if, when placing a chisel'd pumpkin on snow blocks to make a golem, if that golem kept that pumpkin's facial expression?

Neat. I know. You're welcome.

**Comment by warlordjones** [comment]
That would require a custom mob, which is doable but possible out of scope. Can't even make chisel pumpkins work with normal snowmen, as the check is hardcoded.

**Comment by TheCricket** [comment]
Done
