### ISSUE TITLE
Packed Ice Pillar recipe missing

### ISSUE THREAD

**Issue by scyfar** [TheCricket/Chisel-2#261]
There is no recipe for packed ice pillars (or I just cant find it?). Also the reverse recipe to packed ice is missing.

Minecraft: 1.7.10
Forge: 10.13.2.1291
Chisel: 2.3.7.34

**Comment by scyfar** [comment]
Found other blocks missing recipes too:

* stone_snakestone
* stonebricksmooth2
* mossy_templeblock (maybe because of the ballOfMoss, which I have disabled)

**Comment by Drullkus** [comment]
Stonebricksmooth2 is removed.

stone_snakestone is probably chiselable.

I will check them out now.
