### ISSUE TITLE
Crash with dev chisel 2.3.7.80

### ISSUE THREAD

**Issue by crunkazcanbe** [TheCricket/Chisel-2#268]
Like the title says . http://pastebin.com/p8meTphd
I have to go all the way back to Chisel-dev-2.3.7.78 to not get this crash . Going back to this version allows me to start Minecraft again .

Edit I just found the mod causing this by removing 1 mod at a time in a 306 mod mod pack took awhile . Its tinkersconstruct causing this .

**Comment by TheCricket** [comment]
Fixed
