### ISSUE TITLE
minecraft can't open

### ISSUE THREAD

**Issue by nitsuga5124** [TheCricket/Chisel-2#269]
http://pastebin.com/R1Qbd91d

weird texture crash with the full 100% vanilla textures with and without optifine and fastcraft.

fix the realy weird bug :(

**Comment by tterrag1098** [comment]
You are using mcpatcher, and the game is running out of room for textures. This is not a chisel bug.

**Comment by Drullkus** [comment]
Labeled for future reference :P

**Comment by nitsuga5124** [comment]
i am not using the mcpatcher, i only installed forge and add mods to the mods folder (changing some configs)

**Comment by TheCricket** [comment]
You are it's the first line of the crash report.

**Comment by nitsuga5124** [comment]
optifine uses mcpatcher? i take optifine and it work...

**Comment by CptSpaceToaster** [comment]
Optifine and mcpatcher both have similar paths, and while they are two different project, they share old rendering formats.  I'm not sure what the exact details are, but I remember them sharing CTM renderers, and texture formats.  It's possible that one project borrowed from the other early on, and there are still naming conventions that are shared.  

If I had to guess, I'd assume that MCpatcher was first, and then it transformed into Optifine later on once Forge became a bit more stable.

That being said, this sounds like a straight Optifine issue... However, the texture limitation might be graphics card specific.  

Optifine Verison: OptiFine_1.7.10_HD_A4
Chisel: Chisel2-2.3.7.34.jar
**Ahh... here's the kicker:**
OpenGL: Intel 965/963 Graphics Media Accelerator GL version 2.0.0 - Build 8.14.10.1930, Intel

@nitsuga5124,I see you're using an Onboard Intel Accelerated graphics adaptor (likely on a laptop, or onboard motherboard video)  Do you have another graphics card already installed?  There are a couple solutions.

1.) Remove mods, and try to fit inside your limited hardware.
2.) Install/use a more equipped GPU if you have one available.

**Comment by nitsuga5124** [comment]
i update optifine and it work, nothing more...
