### ISSUE TITLE
Creative Tab GUI bug

### ISSUE THREAD

**Issue by crunkazcanbe** [TheCricket/Chisel-2#270]
As the title says . I am using latest DEV version off of Jenkins as of right now . https://imgur.com/YY7ET7P

**Comment by TheCricket** [comment]
As intended

**Comment by CptSpaceToaster** [comment]
Yeah, unless there's some problem here, the text looks good to me.  Was there something that confused you @crunkazcanbe ?

**Comment by TehNut** [comment]
I think it's the Tab name going over the text field. Not really a *bug* just an annoyance to some people.

**Comment by CptSpaceToaster** [comment]
Oh, the whole "Modded Chisel **Blocks**" thing?

**Comment by TehNut** [comment]
Yes, most likely
