### ISSUE TITLE
Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall with Chisel2-2.3.7.34.jar

### ISSUE THREAD

**Issue by sandalle** [TheCricket/Chisel-2#272]
Still getting this warning on load from Issue #197 when using Chisel2-2.3.7.34.jar and Forge 7.10.88.1307.

```
[B#283] 2015/03/23 13:14:44 [INFO]  [13:14:44] [Netty Client IO #8/WARN] [FML]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
```

The mod itself seems to continue functioning.

**Comment by TheCricket** [comment]
Because this warning means absolutely nothing, cobblestone wall is not implemented and is just a place holder. I wish I had a penny for every time I heard this, I would be a billionaire. Sorry to be rude but I get sick of this.

**Comment by sandalle** [comment]
Probably as sick as server admins (such as myself) are of seeing the error when trying to track down issues with a modpack or server, which is probably why it gets reported. :)

**Comment by TehNut** [comment]
No, probably even more since you can look through past issues prior to reporting yourself.

**Comment by sandalle** [comment]
@TehNut , six of one, half a dozen of another. Either way someone is seeing a useless warning and then has to go look it up. I was just trying to be courteous and mentioning I still see this error in my server logs when troubleshooting issues and it can lead me astray. Then for each mod I get to look up every "useless" warning and error to see if it's what's affecting me. *Or* mod authors can remove these useless warnings and errors. Choose your poison. :)

**Comment by MikeLydeamore** [comment]
@sandalle We, as mod devs, has tried to turn off such warnings (such as missing texture exceptions). But it gets us in trouble from the higher powers, and so we just leave them as they are. Unfortunate, but the way it is.
