### ISSUE TITLE
Bug: Chisel Bookshelves Drop Damaged Books

### ISSUE THREAD

**Issue by mcgraj3** [TheCricket/Chisel-2#274]
Breaking any Chisel bookshelf (aside from the vanilla block) adds a damage value to the books dropped. These books cannot be used to re-craft new bookshelves.

For example, testing some of the bookshelves, I broke a Hoarder's Bookshelf. It returned 3 books with the item ID 340:6. These books could not be used in the vanilla bookshelf recipe.

The workaround (for now) is to drop any books with a damage value set by Chisel, get a vanilla book, then pick up the other books to clear the damage values. (Any books picked up will be set to the book in your inventory's damage value.)

**Comment by CptSpaceToaster** [comment]
I thought that was fixed... hmmm odd...

The other solution is to make 15 more book textures, and link them to the forge-ore-dict...

**Comment by TheCricket** [comment]
I swear I fixed this, might be using an old version

**Comment by mcgraj3** [comment]
Just checked my version against what is on Curse and it is the same: Chisel2-2.3.7.34.

**Comment by TehNut** [comment]
That means it's weeks behind the latest source.

Check if it still happens with the latest build [here](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/).

**Comment by CptSpaceToaster** [comment]
Curse has the latest stable releases... we're due for a new one...

Cricket asked me to make another one soon... we'll see if that happens today...

**Comment by CptSpaceToaster** [comment]
update to the latest [Chisel2-2.3.8.35.jar](http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files/2231220)
