### ISSUE TITLE
IMCHandler.java throws exeption even when everything is good

### ISSUE THREAD

**Issue by squ1b3r** [TheCricket/Chisel-2#278]
Hey,

So, I've been playing around Chisel's API and found an issue:

```
		try {
			switch (type) {
			case ADD_VARIATION:
			case REMOVE_VARIATION:
				Block block = (Block) Block.blockRegistry.getObject(data[1]);
				int meta = Short.parseShort(data[2]);
				if (type == IMC.ADD_VARIATION) {
					reg.addVariation(data[0], block, meta, order++);
				} else {
					reg.removeVariation(block, meta, data[0]);
				}
			case REGISTER_GROUP_ORE:
				reg.registerOre(data[0], data[1]);
			default:
				throw new IllegalArgumentException("Invalid IMC constant! How...what...?");
			}
		} catch (Exception e) {
			Chisel.logger.error("Could not handle data {} for IMC type {}. This was sent from mod {}.\n"
					+ "!! This is a bug in that mod !!\nSwallowing error and continuing...",
					value, type.name(), message.getSender());
			e.printStackTrace();
		}
```
Because those `case`'s don't have `break`'s in them it always ends up with `default` even when everything is good and registered or removed. So every time I register a variation I end up with "Invalid IMC constant! How...what...?" despite the fact that all went well in new variations were added and work fine.

To be honest of looks really weird that `ADD_VARIATION` is being handled inside `case REMOVE_VARIATION`

**Comment by tterrag1098** [comment]
Oof, good catch. I'll fix that up later

**Comment by CptSpaceToaster** [comment]
This warrant's a new release when fixed.

**Comment by CptSpaceToaster** [comment]
@squ1b3r tterrag pushed out a fix out in the dev-branch that should hopefully fix everything.

Can you give [this](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/87/) a try to see if everything's good?  Then we can ship version 2.3.9.

**Comment by squ1b3r** [comment]
>Can you give this a try to see if everything's good? Then we can ship version 2.3.9.
Everything works well know. Thanks for the response and quick fix. You guys rock!

p.s. Not trying to teach you to code or anything but why not just do this?:
```
try {
    Block block = (Block) Block.blockRegistry.getObject(data[1]);
    int meta = Short.parseShort(data[2]);

    switch (type) {
        case ADD_VARIATION:
            reg.addVariation(data[0], block, meta, order++);
            break;
        case REMOVE_VARIATION:
            reg.removeVariation(block, meta, data[0]);
            break;
        case REGISTER_GROUP_ORE:
            reg.registerOre(data[0], data[1]);
            break;
        default:
            throw new IllegalArgumentException("Invalid IMC constant! How...what...?");
    }
} catch (Exception e) {
    Chisel.logger.error("Could not handle data {} for IMC type {}. This was sent from mod {}.\n" + "!! This is a bug in that mod !!\nSwallowing error and continuing...", value, type.name(),
            message.getSender());
    e.printStackTrace();
}
```
It's more readable this way and makes more sense IMO

**Comment by CptSpaceToaster** [comment]
Your function would error as it's written:
In your case,  the block and meta instance variables are constructed in all 4 cases, whereas they were only constructed in two prior.

I don't think we can construct a block from `data[1]` in case 3, as the parsed string in that case indicates that the user sent a `group name`, and an `ore`... which would cause quite a ruckus if we attempted to create a block that way.

**Comment by tterrag1098** [comment]
Exactly that, yep

**Comment by CptSpaceToaster** [comment]
Release [2.3.9](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10/36/) with this fixed.
