### ISSUE TITLE
Chisel duplicate glitch

### ISSUE THREAD

**Issue by Radviger** [TheCricket/Chisel-2#280]
Dear chisel developers, I've found a terrible issue with your mod:
Players on my server can duplicate items so simple when they click hotbar key on chisel with the same item they put in.

This a example video:
https://youtu.be/FErKCSTOFuw

Fix it please!

**Comment by 61352151511** [comment]
You must have an outdated chisel, the latest is 2.3.9 I have 2.3.8, With 2.3.8 I can not reproduce this situation.

**Comment by tterrag1098** [comment]
It was fixed in 2.3.7

**Comment by Radviger** [comment]
Thanks!
