### ISSUE TITLE
Crash at Startup using Chisel 2 dev version 2.3.9.88 after updating to AE2 rv20...

### ISSUE THREAD

**Issue by ate0ate** [TheCricket/Chisel-2#281]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 3/28/15 3:11 PM
Description: Initializing game

java.lang.NullPointerException: Cannot add variation in group AECertusQuartz for null block.
	at com.cricketcraft.chisel.carving.Carving.addVariation(Carving.java:152)
	at com.cricketcraft.chisel.Features$1.addBlocks(Features.java:46)
	at com.cricketcraft.chisel.Features.loadBlocks(Features.java:2811)
	at com.cricketcraft.chisel.Features.preInit(Features.java:2880)
	at com.cricketcraft.chisel.Chisel.preInit(Chisel.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.cricketcraft.chisel.carving.Carving.addVariation(Carving.java:152)
	at com.cricketcraft.chisel.Features$1.addBlocks(Features.java:46)
	at com.cricketcraft.chisel.Features.loadBlocks(Features.java:2811)
	at com.cricketcraft.chisel.Features.preInit(Features.java:2880)
	at com.cricketcraft.chisel.Chisel.preInit(Chisel.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3713828264 bytes (3541 MB) / 4140826624 bytes (3949 MB) up to 4140826624 bytes (3949 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 46 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: api.player.forge.RenderPlayerAPITransformer
          - Transformer: api.player.forge.RenderPlayerAPIEnhancerTransformer
          - Transformer: net.smart.core.SmartCoreTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: factorization.coremod.ASMTransformer
          - Transformer: openmods.core.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.CoFHAccessTransformer
          - Transformer: factorization.coremod.FzAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cofh.asm.CoFHClassTransformer
          - Transformer: lumien.randomthings.Transformer.RTClassTransformer
          - Transformer: tterrag.core.common.transform.TTCoreTransformer
          - Transformer: tterrag.core.common.transform.TTCoreTransformerClient
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
          - Transformer: com.rwtema.extrautils.command.CommandASMCore
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4086m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.97.1343 Minecraft Forge 10.13.2.1343 114 mods loaded, 114 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{7.10.97.1343} [Forge Mod Loader] (forge-1.7.10-10.13.2.1343-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	Forge{10.13.2.1343} [Minecraft Forge] (forge-1.7.10-10.13.2.1343-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2-core{rv2-beta-20} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	NotEnoughItems{1.0.4.94} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.94-universal.jar) Unloaded->Constructed->Pre-initialized
	PlayerAPI{1.2} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	RenderPlayerAPI{1.3} [Render Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	RenderPlayerAPIEnhancer{1.3} [Render Player API Enhancer] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	SmartCore{1.0} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
	furnace3d{1.4.0} [Furnace 3D] ([1.7.10] 3D Furnace-1.4.jar) Unloaded->Constructed->Pre-initialized
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized
	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized
	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized
	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) Unloaded->Constructed->Pre-initialized
	koresample{1.7.10-1.2.5} [Kore Sample] (KoreSample-1.7.10-1.2.5.jar) Unloaded->Constructed->Pre-initialized
	dendrology{1.7.10-1.3.0} [Ancient Trees] (AncientTrees-1.7.10-1.3.0.jar) Unloaded->Constructed->Pre-initialized
	appliedenergistics2{rv2-beta-20} [Applied Energistics 2] (appliedenergistics2-rv2-beta-20.jar) Unloaded->Constructed->Errored
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
	Artifacts{1.1.1} [Artifacts] (Artifacts-1.1.1.jar) Unloaded->Constructed->Pre-initialized
	BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
	CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-224.jar) Unloaded->Constructed->Pre-initialized
	ThermalFoundation{1.7.10R1.0.0RC7} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC7-65.jar) Unloaded->Constructed->Pre-initialized
	ThermalExpansion{1.7.10R4.0.0RC7} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC7-149.jar) Unloaded->Constructed->Pre-initialized
	BigReactors{0.4.2A2} [Big Reactors] (BigReactors-0.4.2A2.jar) Unloaded->Constructed->Pre-initialized
	Mantle{1.7.10-0.3.2.jenkins187} [Mantle] (Mantle-1.7.10-0.3.2.jenkins187.jar) Unloaded->Constructed->Pre-initialized
	Natura{2.2.0} [Natura] (natura-1.7.10-98.6a6cca1.jar) Unloaded->Constructed->Pre-initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1146-universal.jar) Unloaded->Constructed->Pre-initialized
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized
	Botania{r1.5-172} [Botania] (Botania r1.5-172.jar) Unloaded->Constructed->Pre-initialized
	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized
	TwilightForest{2.3.4} [The Twilight Forest] (twilightforest-1.7.10-2.3.4.jar) Unloaded->Constructed->Pre-initialized
	ForgeMultipart{1.1.1.326} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.326-universal.jar) Unloaded->Constructed->Pre-initialized
	chisel{2.3.9.88} [Chisel 2] (Chisel2_DEV-2.3.9.88.jar) Unloaded->Constructed->Errored
	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar) Unloaded->Constructed->Pre-initialized
	menagerie{1.0} [menagerie] (dark_menagerie-1.7.10-beta-2.0.jar) Unloaded->Constructed->Pre-initialized
	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized
	endportrecipe{0.1} [End Portal Frame Recipe] (End Portal Recipe-1.7.10-0.1.jar) Unloaded->Constructed->Pre-initialized
	EnderIO{1.7.10-2.2.8.364} [Ender IO] (EnderIO-1.7.10-2.2.8.364.jar) Unloaded->Constructed->Pre-initialized
	EnderStorage{1.4.5.29} [EnderStorage] (EnderStorage-1.7.10-1.4.5.29-universal.jar) Unloaded->Constructed->Pre-initialized
	EnderZoo{1.7.10-1.0.9.19} [Ender Zoo] (EnderZoo-1.7.10-1.0.9.19.jar) Unloaded->Constructed->Pre-initialized
	exnihilo{1.38-21} [Ex Nihilo] (Ex-Nihilo-1.38-21.jar) Unloaded->Constructed->Pre-initialized
	RedstoneArsenal{1.7.10R1.1.0RC7} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC7-69.jar) Unloaded->Constructed->Pre-initialized
	TConstruct{1.7.10-1.8.3.build921} [Tinkers' Construct] (TConstruct-1.7.10-1.8.3.build921.jar) Unloaded->Constructed->Pre-initialized
	exastris{MC1.7.10-1.16-26} [Ex Astris] (Ex-Astris-MC1.7.10-1.16-26.jar) Unloaded->Constructed->Pre-initialized
	extracells{2.2.62} [ExtraCells] (ExtraCells-1.7.10-2.2.62b93.jar) Unloaded->Constructed->Errored
	ExtraUtilities{1.2.2} [Extra Utilities] (extrautilities-1.2.2.jar) Unloaded->Constructed->Pre-initialized
	factorization.notify{1.0} [Factorization Notification System] (Factorization-1.7.10-0.8.89.jar) Unloaded->Constructed->Pre-initialized
	factorization.dimensionalSlice{0.8.89} [Factorization Dimensional Slices] (Factorization-1.7.10-0.8.89.jar) Unloaded->Constructed->Pre-initialized
	factorization{0.8.89} [Factorization] (Factorization-1.7.10-0.8.89.jar) Unloaded->Constructed->Pre-initialized
	factorization.misc{0.8.89} [Factorization Miscellaneous Nonsense] (Factorization-1.7.10-0.8.89.jar) Unloaded->Constructed->Pre-initialized
	FastCraft{1.20} [FastCraft] (fastcraft-1.20.jar) Unloaded->Constructed->Pre-initialized
	Steamcraft{0.28.6} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.6.jar) Unloaded->Constructed->Pre-initialized
	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.7.10-beta-5a.jar) Unloaded->Constructed->Pre-initialized
	GardenCore{1.7.10-1.5.4} [Garden Core] (GardenStuff-1.7.10-1.5.4.jar) Unloaded->Constructed->Pre-initialized
	GardenContainers{1.7.10-1.5.4} [Garden Containers] (GardenStuff-1.7.10-1.5.4.jar) Unloaded->Constructed->Pre-initialized
	GardenStuff{1.7.10-1.5.4} [Garden Stuff] (GardenStuff-1.7.10-1.5.4.jar) Unloaded->Constructed->Pre-initialized
	GardenTrees{1.7.10-1.5.4} [Garden Trees] (GardenStuff-1.7.10-1.5.4.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo] (growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Bees{2.1.0} [Growthcraft Bees] (growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap] (growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
	Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
	imc{1.6} [Improving Minecraft] (Improving Minecraft-1.6.jar) Unloaded->Constructed->Pre-initialized
	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized
	IronChest{6.0.62.29} [Iron Chest] (ironchest-1.7.10-6.0.62.29-universal.jar) Unloaded->Constructed->Pre-initialized
	magicalcrops{4.0.0_BETA_13a} [Magical Crops] (magicalcrops-4.0.0_BETA_13a.jar) Unloaded->Constructed->Pre-initialized
	Mekanism{8.0.2} [Mekanism] (Mekanism-1.7.10-8.0.2.201.jar) Unloaded->Constructed->Pre-initialized
	MekanismGenerators{8.0.2} [MekanismGenerators] (MekanismGenerators-1.7.10-8.0.2.201.jar) Unloaded->Constructed->Pre-initialized
	MekanismTools{8.0.2} [MekanismTools] (MekanismTools-1.7.10-8.0.2.201.jar) Unloaded->Constructed->Pre-initialized
	mythril{1.6} [Mythril mod] (mithril_mod-1.7.2-1.6.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons{1.12.6.18} [NEI Addons] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Botany{1.12.6.18} [NEI Addons: Botany] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|Forestry{1.12.6.18} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|CraftingTables{1.12.6.18} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed->Pre-initialized
	NEIAddons|ExNihilo{1.12.6.18} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.6.18.jar) Unloaded->Constructed->Pre-initialized
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-327.jar) Unloaded->Constructed->Pre-initialized
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-573.jar) Unloaded->Constructed->Pre-initialized
	PetBat{1.3.6} [Pet Bat] (PetBat-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	ProjectE{1.7.10-PE1.4.2} [ProjectE] (ProjectE-1.7.10-PE1.4.2.jar) Unloaded->Constructed->Pre-initialized
	MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Core{4.5.15.75} [ProjectRed] (ProjectRed-1.7.10-4.5.15.75-Base.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transmission{4.5.15.75} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Transportation{4.5.15.75} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.15.75-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Exploration{4.5.15.75} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.15.75-World.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Compatibility{4.5.15.75} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.15.75-Compat.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Integration{4.5.15.75} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Illumination{4.5.15.75} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.15.75-Lighting.jar) Unloaded->Constructed->Pre-initialized
	ProjRed|Expansion{4.5.15.75} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.15.75-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized
	ttCore{MC1.7.10-0.1.1-71} [ttCore] (ttCore-MC1.7.10-0.1.1-71.jar) Unloaded->Constructed->Pre-initialized
	RArm{1.7.10-1.1-23} [Redstone Armory] (RedstoneArmory-1.7.10-1.1-23-universal.jar) Unloaded->Constructed->Pre-initialized
	AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	SmartMoving{15.3} [Smart Moving] (SmartMoving-1.7.10-15.3.jar) Unloaded->Constructed->Pre-initialized
	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized
	StorageDrawers{1.7.10-1.3.5} [Storage Drawers] (StorageDrawers-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized
	thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-474.jar) Unloaded->Constructed->Pre-initialized
	ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0RC7-101.jar) Unloaded->Constructed->Pre-initialized
	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) Unloaded->Constructed->Pre-initialized
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
	witchery{0.23.2} [Witchery] (witchery-1.7.10-0.23.2.jar) Unloaded->Constructed->Pre-initialized
	McMultipart{1.1.1.326} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.326-universal.jar) Unloaded->Constructed->Pre-initialized
	denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
	ForgeMicroblock{1.1.1.326} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.326-universal.jar) Unloaded->Constructed->Pre-initialized
	OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: beta rv2-beta-20 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.0RC7-224
	ThermalFoundation: -[1.7.10]1.0.0RC7-65
	ThermalExpansion: -[1.7.10]4.0.0RC7-149
	Mantle Environment: Environment healthy.
	RedstoneArsenal: -[1.7.10]1.1.0RC7-69
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.0.0RC7-101
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Launched Version: 1.7.10-Forge10.13.2.1343-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.3347, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ate0ate** [comment]
Sorry! Fixed in AE2rv21:)

**Comment by fresser** [comment]
I got this crash on 2 independently computers. Version beta-30, doesn't appeared as fixed anymore?
http://pastebin.com/j04206m8

**Comment by CptSpaceToaster** [comment]
Have you tried the latest beta [Chisel2_DEV-2.4.0.107.jar](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/)

**Comment by fresser** [comment]
Sorry for wasting your time, figured i had 2 version of AE2 installed, haha sorry ;)

**Comment by CptSpaceToaster** [comment]
no problem
