### ISSUE TITLE
Color of Cyan Anti Block Wrong

### ISSUE THREAD

**Issue by chloeprince** [TheCricket/Chisel-2#282]
In the latest update Chisel2_DEV-2.3.9.88.jar, the Cyan Anti Block is now Light Blue. As you can see in this picture, these blocks Used to match. Now the trim is light blue, which are actually Cyan Anti Blocks). Please fix the color of the Anti Blocks so they match the rest of Minecraft's color palette as before. My Skylights look out of place now. Thank you.

![2015-03-29_02 36 46](https://cloud.githubusercontent.com/assets/6889524/6884382/91535baa-d5bd-11e4-9e65-bfdf66669016.png)

**Comment by tterrag1098** [comment]
I warned you @CptSpaceToaster

**Comment by CptSpaceToaster** [comment]
@tterrag1098 ?  What's the issue?
@Dullkus: Why was this recolored? https://github.com/TheCricket/Chisel-2/commit/f9fa6ec129f7fe601e284565ab1f9f1f24d8139d

**Comment by tterrag1098** [comment]
The colors are in the config aren't they?

**Comment by CptSpaceToaster** [comment]
@tterrag1098 Hex block colors are in the config...  Antiblocks are 16 individual textures... Drullkus recolored them for some reason.

**Comment by tterrag1098** [comment]
Ah.

@Drullkus pls

y

**Comment by Drullkus** [comment]
Uhh... wat

**Comment by Drullkus** [comment]
I looked up the differences to remind myself of why I did it. 

![screen shot 2015-03-31 at 3 23 14 pm](https://cloud.githubusercontent.com/assets/5010174/6930637/e81a1cbe-d7b9-11e4-9eed-d4fbd393938f.png)

**Comment by Drullkus** [comment]
What I can do though is to use the old cyan color for the new light blue texture.

**Comment by CptSpaceToaster** [comment]
Hmmm... I always understood [cyan](http://www.colorpicker.com/color/cyan) to be equal parts Blue+Green and [Light Blue](http://www.colorpicker.com/color/light-blue) to be more Blue, than Green (and maybe some Red).

The other changes make sense as a matter of artistic expression.  What might have been purple to me, looks a bit more like Majenta to you, and by all means, please make those kinds of edits!

I think we're backwards on Cyan and Light Blue though...

**Comment by chloeprince** [comment]
Cyan should be cyan, and light blue is light blue. Just please put it back the way it was. They had a unique look and use. Now, meh. 

I liked how they were illuminated, vibrant and bright. Please put it back or offer a separate set of blocks for new and old versions. 

By they way, why are they "anti blocks"? What's their purpose or speciality?

**Comment by chloeprince** [comment]
There is a clear set of hex decimal numbers for the color pallet. 

I think you should stick to the 16 colors of Minecraft pallet. 

It was fine before.

**Comment by CptSpaceToaster** [comment]
@chloeprince and @Drullkus have you ever played [AntiChamber](https://www.youtube.com/watch?v=aGsnm2nOnso)?

The block was meant to be a throwback/reference to the very bright and saturated colors from the game.

**Comment by Drullkus** [comment]
Antichamber was the reason I made these textures! Yes I played it, really good game! :D

**Comment by CptSpaceToaster** [comment]
@Drullkus, I hate to press the issue, but did you get a chance to look at cyan<->light blue?  I think Chloe and I are in agreement that they should be flipped (flipped back?)

**Comment by Drullkus** [comment]
But the light blue blocks are...? :( 
![screen shot 2015-03-31 at 10 05 33 pm](https://cloud.githubusercontent.com/assets/5010174/6934966/2685bfb6-d7f2-11e4-98cf-d9f0c57932f6.png)

**Comment by chloeprince** [comment]
That is not a light blue color. It's cyan. And that color should be assigned to the cyan block. 

The problem is, when people build with your blocks, and then you change them, it changes their designs. In my case, I have used these blocks so much, that the changes on my server are so large it affects too many things.  

You should have 16 color anti blocks and they should follow suit with minecrafts 16 color pallet scheme, except for the fact that anti blocks glow and are vibrant and connect. That makes them awesome.

**Comment by ate0ate** [comment]
I noticed this myself and must say I agree with Chloe. The rest of the antiblocks seem to match vanilla's palette but something is up with the Cyan antiblock now. It definitely makes sense to have the 16 antiblock colors match the 16 vanilla colors for builds.

**Comment by tterrag1098** [comment]
I'm with them. @Drullkus pls just use normal colors

**Comment by Drullkus** [comment]
Alright fine, I'll revert them >:|

**Comment by Drullkus** [comment]
I will keep all other changes but the light blue and cyan will be changed back to Cpt's versions.
