### ISSUE TITLE
Major Dupe Bug. 

### ISSUE THREAD

**Issue by MrHelp** [TheCricket/Chisel-2#283]
*redacted* - warlordjones

**Comment by TehNut** [comment]
Thanks for the 12 second intro on a 33 second video.

**Comment by MrHelp** [comment]
I want help you fix this dupe and i want kill other big project. So i can help you.

**Comment by TehNut** [comment]
Remove the Youtube link. Spreading this isn't helping anybody.

**Comment by warlordjones** [comment]
Investigating

**Comment by MrHelp** [comment]
I not want give dupe easy. I love when people think.

**Comment by MrHelp** [comment]
I will help. it is Stone chisel (TinkerConstruct) + iron. And after Chisel 2

**Comment by warlordjones** [comment]
We know how to replicate the bug, but we don't want others to know. Easy fix. Dangit @Drullkus :P

**Comment by MrHelp** [comment]
Okay)

**Comment by warlordjones** [comment]
Thank you for your eventual cooperation :D

**Comment by MrHelp** [comment]
I can see you more. Other dupe. Want?

**Comment by warlordjones** [comment]
Please send it in private, but yes, unless it is also with TiCon.

**Comment by MrHelp** [comment]
Tomorrow i will

**Comment by MrHelp** [comment]
so...
http://www.youtube.com/watch?v=a7U5yUTEO10&feature=youtu.be

**Comment by TehNut** [comment]
STOP POSTING YOUTUBE LINKS.

**Comment by MrHelp** [comment]
Well. Maybe tomorrow i will send you new dupe again.

**Comment by MrHelp** [comment]
TehNut - Okay. How you want see it?

**Comment by warlordjones** [comment]
Ok. What he means is that you should stop publicly saying how to dupe stuff, and instead report it to one of us privately - that's standard procedure for dupe bugs.

**Comment by MrHelp** [comment]
sorry.. but i don't know how i can send privately message here.. Your answer its too hight speed. It don't think what anybody can see that in 30 seconds

**Comment by MrHelp** [comment]
Wait me 10 minutes. Give you a new dupe

**Comment by MrHelp** [comment]
http://www.youtube.com/watch?v=nA0idmveFzU&feature=youtu.be

**Comment by TehNut** [comment]
Click this link:

https://webchat.esper.net/?channels=chisel

Find an OP. PM them these youtube links. Stop posting them here.

**Comment by tterrag1098** [comment]
Why would you post a THIRD video??

**Comment by CptSpaceToaster** [comment]
MrHelp
Chisel Version?
[ ]Chisel2-2.3.7.34.jar?
[ ]Chisel2-2.3.8.35.jar?
[ ]Chisel2-2.3.9.36.jar?

**Comment by MrHelp** [comment]
2.3.9

**Comment by CptSpaceToaster** [comment]
Here we go, this latest dev build should fix it:
http://ColoredLightsCore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/91/

You'll want the: [Chisel2_DEV-2.3.9.91.jar](http://coloredlightscore.us.to:8080/job/Chisel-2%20v1.7.10-Dev/91/artifact/build/libs/Chisel2_DEV-2.3.9.91.jar)

**Comment by MrHelp** [comment]
thx. Will test it

**Comment by natedog1177** [comment]
Can i know the issue? Currently running a direwolf20 server, found someone duping, the only signs i have to go off of are golden bags of holding, backpacks from projectred, satchel from thermal expansion, and 3 diamond chisels.

**Comment by TheCricket** [comment]
Just update the mod

**Comment by natedog1177** [comment]
cant, its a public server on the direwolf back, if i update the mod, no one would be able to join unless they manually updated it as well, server already runs on the newest build 1.2.1, so hasnt added the fix for this thing yet.

**Comment by CptSpaceToaster** [comment]
@natedog1177: Please update the mod on both server and client-side, and see if you can repeat it.

If you can, then we will pay attention to this issue, but this should have been fixed in the latest release: http://www.curse.com/mc-mods/minecraft/225236-chisel-2#t1:other-downloads

**Comment by natedog1177** [comment]
If you read my original comment, i say, i wasnt the one that did it, someone else that plays on my server has, and i want to try to replicate it and see if this is, or is not the issue. So updating the mod isn't an option since its a 10-30 constant player public server, I just need to know if i should ban the chisel from use if it is an issue in the version. Chisel2-2.3.7.34

**Comment by TheCricket** [comment]
As we said, update or we cannot help. Banning anything is never good, there is always a workaround.

**Comment by CptSpaceToaster** [comment]
@natedog1177: Chisel2-2.3.7.34 will most likely have the issue.  If you continue to run the out-dated version, then you may have trouble.  To protect your server, we saying the only option is to update, or remove Chisel2.  I don't understand why you can't update your mod, however that's another discussion.

Do you have any other questions?  If not, I'm going to lock the issue.

**Comment by natedog1177** [comment]
The reason i can't explain is that I'm running a full time public server, and updating it would require any potential new player to manually change out the mod. I'll just keep it out of the server till the pack creator of the direwolf20 updates the mod in the pack itself. thank you for both of your time.

**Comment by CptSpaceToaster** [comment]
Sounds like someone should contact the maintainer of DireWolf20.
