### ISSUE TITLE
Maybe bug?

### ISSUE THREAD

**Issue by MrHelp** [TheCricket/Chisel-2#285]
Chisel 2 work on private region.

**Comment by TheCricket** [comment]
What does this even mean?

**Comment by CptSpaceToaster** [comment]
Ooo!  I think I can try to decipher:

On vanilla servers, the center area around the spawn is protected according to the [spawn radius](http://minecraft.gamepedia.com/Server.properties#spawn-protection).  I think MrHelp was saying that is still allowed to function, even if the targeted block is inside spawn protection.

Things to check:
1.) Is this even the case?
2.) Does it change if the player stands inside spawn protection, versus outside.

**Comment by TheCricket** [comment]
I think he is talking about like a grief prevention plugin, which if the case it's not our fault we don't work with bukkit.

**Comment by linkinkov** [comment]
but you can add to config option for disable left click for all chisel or with left click use forge block break events

**Comment by CptSpaceToaster** [comment]
@linkinkov I'm not able to understand what you are trying to say...

**Comment by MrHelp** [comment]
Yes. I mean plugin WorldGuard. And i see you answer. But CptSpaceToaster right too. In server,propertiens we have function - spawn radius. It is defend spawn. But chiesel work in this place and can edit block.

**Comment by TheCricket** [comment]
I will not be fixing this, this is not my problem that we don't work with bukkit, never meant to, never wanted to.

**Comment by MrHelp** [comment]
Okay man. I understand. Closed

**Comment by CptSpaceToaster** [comment]
@Cricket, this sounds like we're still stomping on vanilla though.....

**Comment by Drullkus** [comment]
Closed due Cricket's verdict
