### ISSUE TITLE
Same crash as #203 but not with Railcraft; on starting new world cannot load

### ISSUE THREAD

**Issue by cocopuffs99** [TheCricket/Chisel-2#292]
EDIT: On more searching found out MANY other people posting this same error online (100+ different links for different modpacks just on the first search...none of them can start their game!)

Please dont close this issue like #203 and then nobody looks at it and ignores it for all the people that is game-breaking.  Additionally deleting Chisel 2 runs other errors and can't even start Minecraft...the only way right now to fix is to never start using Chisel in the first place/completely delete and reinstall all mods/configs for MC modded... which is a shame.

Hey Guys!  First off thanks for a great mod.  Correct me if I'm wrong, but I think I've found a major bug- It seems if you had a mod previously and then deleted it, and the configs for that mod, but had it prior (even on starting a completely new world) the game will not let you load a map unless you reinstall those mods because Chisel throws errors for the blocks which the previous mod had; and this causes FML server to stop (and thus can't even start a new game/world- if I try to start one it has the error occur and brings me back to the menu screen at the start of loading up Minecraft, and doesn't even register that I tried to start a new world).

Other people are also experiencing the same error - I searched around but couldn't find a workaround or fix.  Any ideas? (http://www.minecraftforum.net/forums/support/modded-client-support/2392926-world-wont-open)

[16:53:56] [Server thread/INFO] [FML/]: Applying holder lookups
[16:53:56] [Server thread/WARN] [FML/]: Unable to lookup chisel:cobblestoneWall for public static com.cricketcraft.chisel.block.BlockMarbleWall com.cricketcraft.chisel.init.ChiselBlocks.cobblestoneWall. Is there something wrong with the registry?
[16:53:56] [Server thread/WARN] [FML/]: Unable to lookup chisel:obsidian2 for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.obsidian2. Is there something wrong with the registry?
[16:53:56] [Server thread/WARN] [FML/]: Unable to lookup chisel:bloodRune for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodRune. Is there something wrong with the registry?
[16:53:56] [Server thread/WARN] [FML/]: Unable to lookup chisel:bloodBrick for public static com.cricketcraft.chisel.block.BlockCarvable com.cricketcraft.chisel.init.ChiselBlocks.bloodBrick. Is there something wrong with the registry?
[16:53:56] [Server thread/INFO] [FML/]: Holder lookups applied
[16:53:56] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppedEvent to mod mcp
[16:53:56] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppedEvent to mod mcp
[16:53:56] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppedEvent to mod FML
[16:53:56] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppedEvent to mod FML
[16:53:56] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppedEvent to mod Forge
[16:53:56] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppedEvent to mod Forge

**Comment by TheCricket** [comment]
So you need to manually fix your world, or use the startup parameter. This is a problem with any modded world and not specifically with chisel. Those unable to lookups don't actually cause any problems. If you have any further questions feel free to ask.

**Comment by tterrag1098** [comment]
This is not related to #203 in any way. This part of the log is irrelevant, you have not posted any real error.

**Comment by tterrag1098** [comment]
>Please dont close this issue like #203 and then nobody looks at it and ignores it for all the people that is game-breaking.

The heck? I fixed that issue almost immediately after it was posted.

**Comment by cocopuffs99** [comment]
Thanks for the heads up! This is happening when I try to make any world - and it just resets the game back to the start menu without saving or registering the world.  So I cant manually fix the world because it doesnt exist. What startup parameters should I be using? I tried to check how to fix it myself online and I see no fix but that this is happening to a lot of people. I didnt have this error before I started using Chisel 2 and the error refers directly to this mod so It seems that this mod is causing it from my best guess!

**Comment by tterrag1098** [comment]
WHAT ERROR. You have not given us a proper log that says ANYTHING about
chisel being the cause. Plesae provide the ENTIRE crash log, not just the
portion  you think is important.

**Comment by cocopuffs99** [comment]
There's no crash log because the game doesn't crash- I've been saying it doesn't start/and you can't create any worlds.  I will load it again and reproduce the error and then paste a link for the fml log in a few mins.  

In the meantime if you Google even "Unable to lookup chisel:bloodBrick" you will see that over 500+ people already posted about this problem and its not something new, but also has been posted in #203 and I don't know programming code but it seems its the same problem, before #203 was closed with no real fix but saying that Railcraft has to be updated, and lots of people posted there who had the same error, just like me, who aren't even using Railcraft.  

There, the issue was closed not because it was specifically fixed but blamed on another mod and listed as another "useless crash message/reminder/whatever".  No specific fix was ever made but the issue was closed.  The whole point of Github is to post bugs in a collaborative way and try to fix them, not to ignore and be rude to people.

**Comment by TehNut** [comment]
>In the meantime if you Google even "Unable to lookup chisel:bloodBrick" you will see that over 500+ people already posted about this problem and its not something new, 

If you would read what the devs are saying, the `Unable to lookup chisel:bloodBrick` ***IS NOT AN ISSUE***

**Comment by cocopuffs99** [comment]
Here is the fml log (too large for pastebin): http://www.filedropper.com/fmlchiselbug

Here is the ATLauncher log: http://paste.atlauncher.com/view/563fa7ad

**Comment by TehNut** [comment]
Please go read your log and close this issue.

**Comment by cocopuffs99** [comment]
I'm sorry I have read my log but I don't know what the error is.  That's why I'm posting here, it seems to be a bug.  If you have any insight into it please let me (and the rest of the MC world having this error) know.

**Comment by TehNut** [comment]
http://tehnut.info/share/H9L6t8ZXM.mp4

**Comment by cocopuffs99** [comment]
I updated Thermal Expansion and I am still getting the same error!  Not sure why its still happening but thanks for the tip.  For the meantime I am deleting Chisel 2 from my modpack.  I may try it at a later time when it is compatible with modded 1.7.10 or later.  Thanks

**Comment by TehNut** [comment]
... It ***IS*** compatible. Your crash is being caused by CoFH. Go ask them.

Whatever, I don't care. It's a waste of time to talk to brick walls.

**Comment by tterrag1098** [comment]
@cocopuffs99 You've had multiple chisel devs tell you it's not caused by chisel. You refuse to listen to anything anyone says and instead continue to talk as if you know everything. It's your choice to remove the mod but it's the wrong solution to the problem. But I don't care anymore.

**Comment by CptSpaceToaster** [comment]
1. Chisel adds a ton of blocks...
2. Removing Chisel from the modpack appears to solve the issue.
3. Forge is throwing an NPE at a [getFluidID()](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/FluidRegistry.java#L117-L120)  

Are we filling up the block id slots?  Is ThermalExpansion trying to register a fluid, and failing to do so?

**Comment by cocopuffs99** [comment]
@CptSpaceToaster thanks for the heads up.  I will try it again with forge (1370) and check.

**Comment by CptSpaceToaster** [comment]
@cocopuffs99 Forge (1291) would be preferable.

**Comment by cocopuffs99** [comment]
I will try it with Forge (1291) and get back to you

**Comment by Drullkus** [comment]
I heard an updated vers of ExU requires 1355? :\

**Comment by CptSpaceToaster** [comment]
Figures.
We'll have to update Chisel to a later version of forge here.

Thanks for being patient with us @cocopuffs99!
Have a great day!

**Comment by cocopuffs99** [comment]
No prob! Thanks for checking on it for me. I couldnt get MC to work with Forge 1291 bc of the Forge 1355 dependency for another mod.  I tried Chisel 2 today with Forge 1373 for my 1.7.10 modpack to see and it seems to be working fine- I couldn't reproduce the error in that version.

**Comment by tterrag1098** [comment]
Chisel should have no problems with newer versions of forge and there is no reason to compile against them either.

**Comment by Drullkus** [comment]
@tterrag1098 Unless we had added Chiselable Fluids -- Thank god we didn't! :3
