### ISSUE TITLE
Feature Request: Config Option for Cross Mod Recipes

### ISSUE THREAD

**Issue by Keridos** [TheCricket/Chisel-2#294]
It would be nice to have config options for certain crossmod stuff. For example you can convert vanilla glass to quite clear glass from enderio that usually is made out of 4 nether quartz. That is not disableable as far as I can see but pretty OP.

**Comment by tterrag1098** [comment]
Quite clear glass is just sand, nothing wrong with that. These items are
added due to the ore dictionary, if you don't want them in there, the mod
author shouldn't have registered them to be equal.

**Comment by Keridos** [comment]
Derp, did not see that....
