### ISSUE TITLE
Chisel latency issue

### ISSUE THREAD

**Issue by SirWilli** [TheCricket/Chisel-2#298]
hey,
it seems that there is the same issue with chisels like with the project red backpacks (https://github.com/MrTJP/ProjectRed/issues/744).

-Explanation Redacted-

Works with both chisels.

**Comment by CptSpaceToaster** [comment]
@SirWilli What version of chisel are you using?  We fixed something a little like this.

**Comment by SirWilli** [comment]
Chisel2-2.3.9.36

**Comment by CptSpaceToaster** [comment]
Please try the [latest version](http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files/2233102), and check if your issue is repeatable.  I'm going to remove the instructions on how to repeat the glitch to avoid future abuse.

**Comment by SirWilli** [comment]
Okay, I will have to ask someone first as my ping is not high enough^^

**Comment by SirWilli** [comment]
Confirmed, fixed in latest version. Thanks.
