### ISSUE TITLE
Config option to disable x -> mossy 

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [TheCricket/Chisel-2#303]
I'd like to have an option to disable any stone being able to be converted into mossy variants.

**Comment by Yulife** [comment]
Doable with Modtweaker2 as well :)

**Comment by Choonster** [comment]
In the latest release (2.3.10), there's already an option to disable Stone/Stone Brick to Mossy Stone Brick conversion (`general -> allowBrickToMossyInChisel`). Cobblestone and Mossy Cobblestone can't be converted to each other.

In the latest dev version (103), the same option exists (though putting Stone in the Chisel crashed the game). Cobblestone and Mossy Cobblestone still can't be converted to each other.

**Comment by Unrepentant-Atheist** [comment]
Where be dev builds, yo?!

**Comment by TehNut** [comment]
What is a [README](https://github.com/TheCricket/Chisel-2#jenkins)?
