### ISSUE TITLE
Build 103 - Crash when Stone is placed in Chisel

### ISSUE THREAD

**Issue by Choonster** [TheCricket/Chisel-2#304]
Chisel version: 2.4.0.103 (latest Jenkins build)
Crash report: https://gist.github.com/Choonster/549abf227d792d536918

Steps to reproduce:
- Obtain Stone and any Chisel (Iron, Diamond or Obsidian)
- Open Chisel GUI and attempt to place Stone in the item slot
- Game crashes

Attempting to open Chisel GUI with Stone already in item slot causes the same crash.

**Comment by tterrag1098** [comment]
Try build 104 when it is built

**Comment by Choonster** [comment]
Unfortunately 104 has a new issue: #308.

**Comment by Choonster** [comment]
This has been fixed in build 107.
