### ISSUE TITLE
Dev build 108 crash at startup (Ancient Trees compatibility?)

### ISSUE THREAD

**Issue by ate0ate** [TheCricket/Chisel-2#313]
I tried updating to a more recent dev build after using build 100 for quite a while and now I get this crash at startup. Ancient Trees (dendrology) is clearly mentioned, but I do not know if the fault lies on their end or on Chisel's. Thanks:)

http://pastebin.com/cj6f38vP

**Comment by tterrag1098** [comment]
Errr, Ancient Trees is doing some very big no-nos in his code. Talk to @ScottKillen

**Comment by ScottKillen** [comment]
@tterrag1098 is not responsible for the crashes in Ancient Trees. It is currently not possible to support both the release and dev version.

I had to create my own API in order support the current release version. I am very excited about the new chisel API. I will fix the crash in Ancient Trees once a new release version is out.

Reference: MinecraftModArchive/Dendrology#31

**Comment by CptSpaceToaster** [comment]
:+1: Thanks for the reply Scott!
