### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xee1** [TheCricket/Chisel-2#315]
Hi, with Chisel2-2.3.10 this appear in console:
https://gist.github.com/Xee1/a25935271e509eb3c8ae

**Comment by TehNut** [comment]
It's nothing.

**Comment by TheCricket** [comment]
This is not a bug, please anyone never put this as an error again

**Comment by CptSpaceToaster** [comment]
Maybe we should remove the bogus message from the log?

**Comment by Drullkus** [comment]
Just add "This is not an error!"? :s

**Comment by tterrag1098** [comment]
We have no control over this logging and when it fires. There is nothing we can do.
