### ISSUE TITLE
Concrete creates unusable doorways and unintended movements

### ISSUE THREAD

**Issue by ZeekDaGeek** [TheCricket/Chisel-2#412]
https://github.com/Chisel-2/Chisel-2/issues/409

Apparently closed because "The situation you have just described can never occur" without any testing whatsoever.

http://zeekdageek.tv/ss/AUtqX.png
You can put doors on concrete.

http://zeekdageek.tv/ss/KjV2t.png
You can have openings that are one wide as well, this is still a doorway.

This is still a bug and the issue was closed too early. Both of these instances are affected by the bug.

I challenge you to make a room that has a concrete floor and a door way you go through frequently and tell me it's not a bug. It's annoying as hell. You shouldn't want to piss of players by making them unable to control their character like it's intended and instead you go skating out of control.

This bug also exists when you walk normally on concrete. Press forward then try to walk backwards, you will continue to move forward slowly. Moving on concrete is seriously screwed up to the point that the block is useless unless the bugs are fixed.

---

Also it seems like bad practice to lock tickets, usually I'm able to post on tickets that are closed if there's additional information to add to prevent doubles like this.

**Comment by TehNut** [comment]
As you were told in the other issue, this is _not_ a bug. Just a side effect caused by Concrete having the player sink into it by 1/16 of a block. It happens with Soul Sand, too.

**Comment by TheCricket** [comment]
You know you can just turn the speed thing off and viola you can now walk through doorways. We have everything be configurable for a reason. I even put joke configs because people were pissed off because of the tooltips on some blocks.

**Comment by tterrag1098** [comment]
Kinda defeats the purpose if it doesn't speed the player up though, no?

**Comment by TheCricket** [comment]
Well the block still functions as a decorative flooring option. I will say that it needs to be touched up a little one the function it is kinda dumb how it works currently

**Comment by ZeekDaGeek** [comment]
The problem is not with soul sand mechanics or bounding issues or anything like that though. The bug is a result of the way GeneralChiselClient.speedupPlayer() is implemented.

It takes your current velocity and forces the effects of Concrete speed modifiers on that fixed amount, concrete should effect acceleration and the maximum amount that you can accelerate too in order to allow the character to move properly.

Lets take the most basic instance of the bug. You move forward on the concrete and then instantly hold back. If you do this your character will skate forward, and your backwards movement is not able to overcome the fixed forward velocity that is being set on you. The only way to overcome this is let your velocity fall below the velocity modifier before attempting to in an opposite direction.

What should happen is your velocity should be 0 when you hit Back (to prevent the surface from feeling like ice) then you should start to accelerate backward. That doesn't happen.

---

EDIT:

In math with numbers that aren't accurate:

When you press Forward you move forward at a default of 1 unit per second. Concrete makes you move forward 1.5x faster so you are going 1.5 units per second. You press Back and hold Back and you the net result is moving forward at 0.5 units per second. You will continue to move forward at 0.5 units per second until you let go of all keys.

There is no continuing attempts for the function to keep increasing or decreasing your velocity until it reaches the maximum it should.

---

EDIT 2:
I'm also well aware of the fact that you can disable the speed boost effects and everything, and I have used a more attractive block for flooring. I wanted to use Concrete not because it's the prettiest but because it gives a buff.

As a result of a bug I'm on the issue tracker, posting the problem hoping to spark a discussion about how to fix the issue. Instead it feels like the problem is just getting dismissed and ignored by people who haven't even tried to replicate it, which feels a little disappointing honestly.

I'm not trying to attack you guys, there's no reason to seem defencive or anything.

**Comment by tterrag1098** [comment]
See the above referenced commit, I have redone the concrete so that it no longer needs the player to "sink" into it, and improved the math so that it applies to all directions properly.

**Comment by tterrag1098** [comment]
Here it is in action: http://gfycat.com/MerryPotableEasternnewt

And here is proving your specific issue is fixed: http://gfycat.com/PlumpFrequentEkaltadeta

**Comment by elfifae** [comment]
And thus Michael Jackson's tortured soul can rest in peace once again.

**Comment by Drullkus** [comment]
:( :( :(

On Sep 14, 2015, at 06:23 PM, tterrag1098 notifications@github.com wrote:

Here it is in action: http://gfycat.com/MerryPotableEasternnewt
And here is proving your specific issue is fixed: http://gfycat.com/PlumpFrequentEkaltadeta
