### ISSUE TITLE
Blood altar doesn't work with chiseled beacons

### ISSUE THREAD

**Issue by rikai** [TheCricket/Chisel-2#415]
I was trying to make a more aesthetically pleasing blood altar (using different beacons that give off different light, but apparently only the vanilla beacon works to make a tier 5 blood altar.

It'd be nice if chiseled beacons could work as well, since they're functionally equivalent and require the actual beacons to make anyway. :)

Edit: Also of note, probably caused by the same thing, are that chiseled glowstone and bloodstone also reduce the altar level, as they're not seen as valid blocks.

Crossposted at WayofTime/BloodMagic#459 since i'm not sure which mod is at fault.

**Comment by Drullkus** [comment]
I'm certain this is only doable on @WayOfTime's side

About the Glowstone and Bloodstone: It would help if there were API hooks inside BM. idk if there are.

**Comment by TheCricket** [comment]
of course they don't work he checks for vanilla beacons :P

**Comment by TehNut** [comment]
I am currently submitting a PR to BloodMagic to fix this.

![It works!](http://i.imgur.com/zVgWbxe.png)

**Comment by TehNut** [comment]
This has been merged into BM and can be closed, now.
