### ISSUE TITLE
[1.7.10] ThermalExpansion Cache Dupe Chisel

### ISSUE THREAD

**Issue by ghost** [TheCricket/Chisel-2#418]
https://youtu.be/xUGbq7IuMDw

**Comment by Eufranio** [comment]
Is not fixed.

**Comment by Drullkus** [comment]
Try reproducing it in 2.9.5: http://minecraft.curseforge.com/projects/chisel/files/2287442

**Comment by ghost** [comment]
fixed in newer versions

**Comment by Drullkus** [comment]
Ah, glad to hear :)
