### ISSUE TITLE
[Enhancement] Resource Pack for Upscaled x32 and x64 Textures

### ISSUE THREAD

**Issue by mikeloeven** [TheCricket/Chisel-2#419]
Could the chisel 2 team please release a upscale 32 and 64X resource pack. when using Chisel 2 with any HD textures the difference in resolution creates a obvious clash between Chisel blocks and vanilla blocks. With the ability to stack resource packs it should be feasible to create such a pack especially since most texture editing tools can upscale automatically

**Comment by TehNut** [comment]
Why not ask your resource pack dev to support Chisel instead..? That's the whole point of them...

**Comment by Drullkus** [comment]
It's not as easy as saying "scale up and enhance". Go bug the guys at @F32Organization instead :P

**Comment by TheCricket** [comment]
if you made your own texture pack you can simply make one for this mod

**Comment by mikeloeven** [comment]
@Drullkus Not really a huge faithful fan

The reason i was asking here was because i like the design of the default textures i was just hoping you could make them a bit sharper 

but if you guys know of any resource packs for the mod i would definitely appreciate some links

**Comment by Drullkus** [comment]
The only guys I approve of are Sphax, and the faithful 32x is the one I recommend for something that hits close to home as for original but upres textures
