### ISSUE TITLE
Chisel2-2.5.1.44 crash

### ISSUE THREAD

**Issue by Lucifer123131** [TheCricket/Chisel-2#420]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 09.10.15 22:00
Description: Initializing game

java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Triple
    at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:193)
    at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:457)
    at com.cricketcraft.chisel.api.carving.VariationInfoBase.registerIcons(VariationInfoBase.java:61)
    at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:202)
    at com.cricketcraft.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:71)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:455)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:97)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:83)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Triple
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 17 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:193)
    at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:457)
    at com.cricketcraft.chisel.api.carving.VariationInfoBase.registerIcons(VariationInfoBase.java:61)
    at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:202)
    at com.cricketcraft.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:71)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:455)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:97)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:83)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1275461888 bytes (1216 MB) / 2134114304 bytes (2035 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 8 total; -Xmx3072M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xms2G -Xmx4G -Xincgc
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 112 mods loaded, 112 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448.jar) 
    UCH Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448.jar) 
    UCH AppleMilkCore{1.1.0} [AppleMilkCore](minecraft.jar) 
    UCH appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCH Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCH NotEnoughItems{1.0.4.107} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCH PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore](minecraft.jar) 
    UCH technomCore{0.12.0A} [Technomancy Core](minecraft.jar) 
    UCH ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCH OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCH malisiscore{1.7.2-0.9.1} [Malisis Core](MalisisDoors-Core-1.7.10.jar) 
    UCH bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCH Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCH Backpack{2.0.0} [Backpack]([mcdownloads.ru] backpack-2.0.0-1.7.x.jar) 
    UCH AmnesiaDecorations{1.1.1} [Amnesia Decorations](AmnesiaDecorations-1.7.10-1.1.1.jar) 
    UCH DCsAppleMilk{1.7.10_2.8e} [Apple&Milk&Tea!](AppleMilkTea2-1.7.10_2.8e.jar) 
    UCH DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT](AppleMilkTea2-1.7.10_2.8e.jar) 
    UCH appliedenergistics2{rv2-stable-1} [Applied Energistics 2](appliedenergistics2-rv2-stable-1.jar) 
    UCH gibby_dungeons{1.2} [Arcana RPG](Arcana RPG 1.2 - 1.7.10.jar) 
    UCH ATG{0.10.0} [Alternate Terrain Generation](ATG-1.7.10-0.12.0.jar) 
    UCH BetterFoliage{0.9.11b} [Better Foliage](BetterFoliage-0.9.11b.jar) 
    UCH BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft[v1.10.6][MC1.7.10].jar) 
    UCH CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCH Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCH ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCH ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCH BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UCH bigtrees{1.6.4} [BigTrees](BigTrees-Mod-1.7.10.jar) 
    UCH BuildCraft|Core{7.0.22} [BuildCraft](buildcraft-7.0.22.jar) 
    UCH BuildCraft|Silicon{7.0.22} [BC Silicon](buildcraft-7.0.22.jar) 
    UCH BuildCraft|Transport{7.0.22} [BC Transport](buildcraft-7.0.22.jar) 
    UCH BuildCraft|Builders{7.0.22} [BC Builders](buildcraft-7.0.22.jar) 
    UCH BuildCraft|Robotics{7.0.22} [BC Robotics](buildcraft-7.0.22.jar) 
    UCH BuildCraft|Energy{7.0.22} [BC Energy](buildcraft-7.0.22.jar) 
    UCH BuildCraft|Factory{7.0.22} [BC Factory](buildcraft-7.0.22.jar) 
    UCH CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCH Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCH Waila{1.5.10} [Waila](waila-1.7.10.jar) 
    UCH TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCH DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V9b.jar) 
    UCH ChromatiCraft{1.0} [ChromatiCraft](ChromatiCraft 1.7.10 V9b.jar) 
    UCH DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) 
    UCH PTRModelLib{1.0.0} [PTRModelLib](Decocraft-2.1.1_1.7.10.jar) 
    UCH props{2.1.1} [Decocraft](Decocraft-2.1.1_1.7.10.jar) 
    UCH DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UCH endercore{1.7.10-0.1.0.23_beta} [EnderCore](EnderCore-1.7.10-0.1.0.23_beta.jar) 
    UCH EnderIO{1.7.10-2.3.0.414_beta} [Ender IO](EnderIO-1.7.10-2.3.0.414_beta.jar) 
    UCH EnderStorage{1.4.7.33} [EnderStorage](EnderStorage-1.7.10-1.4.7.33-universal.jar) 
    UCH EnderZoo{1.7.10-1.0.15.32} [Ender Zoo](EnderZoo-1.7.10-1.0.15.32.jar) 
    UCH extracells{2.2.64} [ExtraCells](ExtraCells-1.7.10-2.2.64b96.jar) 
    UCH GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.344.jar) 
    UCH GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.344.jar) 
    UCH GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](Grimoire-of-Gaia-3-Mod-1.7.10.jar) 
    UCH Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) 
    UCH Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) 
    UCH Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) 
    UCH Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) 
    UCH Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) 
    UCH Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) 
    UCH Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) 
    UCH Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) 
    UCH Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) 
    UCH gud_thaumicnei{1.3.0} [Thaumic NEI](gud_thaumicnei-1.3.0.jar) 
    UCH HardcoreEnderExpansion{1.8.3} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar) 
    UCH inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks [1.7.10].jar) 
    UCH IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCH JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCH journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCH magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops](magical-crops-1.7.10.jar) 
    UCH malisisdoors{1.7.2-1.0.2} [Malisis' Doors](MalisisDoors-Mod-1.7.10.jar) 
    UCH MorePlanet{1.2.9} [More Planets](More-Planets-1.7.10-1.2.9.jar) 
    UCH necromancy{1.7.2} [Necromancy](Necromancy-1.7.10.jar) 
    UCH NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCH neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCH NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    UCH OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCH OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCH RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCH RedstonePasteMod{1.6.2} [Redstone Paste](Redstone-Paste-Mod-1.7.10.jar) 
    UCH SGCraft{1.9.3} [Greg's SG Craft](SGCraft-1.9.3-mc1.7.10.jar) 
    UCH ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-164.jar) 
    UCH benway_knowledge{0.1.4} [Thaumaturgical Knowledge](Thaumaturgical Knowledge-0.1.4.jar) 
    UCH thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCH thaumicbases{1.3.1710.2} [Thaumic Bases](ThaumicBases-1.3.1710.4.jar) 
    UCH thaumicenergistics{0.8.10.10} [Thaumic Energistics](thaumicenergistics-0.8.10.10.jar) 
    UCH ThaumicHorizons{1.1.5} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.6.jar) 
    UCH erebus{0.3a} [Erebus](TheErebus-0.3a.jar) 
    UCH ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCH TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCH TravellersGear{1.16.5} [Traveller's Gear](travellersgear-1.7.10-1.16.5.jar) 
    UCH sgs_treasure{3.0.4} [SGS Treasure!](Treasure-3.0.4-1.7.10.jar) 
    UCH TwoGraves{1710.1.0} [Graves](TwoGraves-Mod-1.7.10.jar) 
    UCH UnicodeFontFixer{1.1.5-mc1.7.10} [UnicodeFontFixer](UnicodeFontFixer-1.1.5-mc1.7.10.jar) 
    UCH wailafeatures{0.0.3} [WAILA Features](WAILA-features-1.7.10-0.0.3.jar) 
    UCH wawla{1.3.1} [What Are We Looking At](Wawla-1.3.1-1.7.10.jar) 
    UCH wildcaves3{0.4.3.6} [Wild Caves 3](Wild-Caves-Mod-1.7.10.jar) 
    UCH WTFCore{1.61} [WhiskyTangoFox's Core](WTFCore-1.7.10_v1.61.jar) 
    UCH CaveBiomes{1.4} [WhiskyTangoFox's CaveBiomes](WTFCaveBiomes-1.7.10_v1.401.jar) 
    UCH IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UCH technom{0.12.0A} [Technomancy](Technomancy - 0.12.0A - 1.7.10.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon HD 7800 Series'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.0-12
    ThermalDynamics: -[1.7.10]1.1.0-161
    EnderIO: Found the following problems with your installation: "Optifine is installed. This is NOT supported." This may have caused the error. Try reproducing the crash WITHOUT this/these mods before reporting it.
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: ForgeOptiFine 1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 7800 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [ThaumcraftHD_0.6.zip, faithful32packOptiFine]
Current Language: Русский (Россия)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Drullkus** [comment]
Redownload your base game and see if that forces a redownload of the game libraries.

Also [get the latest version.](http://minecraft.curseforge.com/projects/chisel/files/2260887)

**Comment by tterrag1098** [comment]
No, update forge.

**Comment by TheCricket** [comment]
Update forge

**Comment by Lucifer123131** [comment]
Update chisel helped

**Comment by TheCricket** [comment]
both
