### ISSUE TITLE
Feature Request: Shift + Left Click to go back a pattern

### ISSUE THREAD

**Issue by wooby6** [TheCricket/Chisel-2#423]
As the title states,

I'm always frustrated that when manually chiselling a block (left click on a block)
1 accidental click later & you have to cycle back to it, sure you could just pick up the block
but what if its a hard to pick up block say obsidian. you see where I'm going with this.

**Comment by tterrag1098** [comment]
See: https://github.com/Chisel-Team/Chisel/pull/6

**Comment by TheCricket** [comment]
I did it
