### ISSUE TITLE
Chisel Corrupted My World..

### ISSUE THREAD

**Issue by SwedzNet** [TheCricket/Chisel-2#424]
Chisel2-2.3.7.34
Forge10.13.4.1448-1.7.10

I was playing on my server and then it crashed all of a sudden. I booted it back up, giving me this error.
![GitHub Logo](http://i.imgur.com/jmfXozN.png)
Please help :(

**Comment by Choonster** [comment]
"Unable to lookup ... Is there something wrong with the registry?" is just a warning that's always displayed, it has nothing to do with the world corruption. The corruption could have been caused by any mod.

Do you have a backup you can restore?

**Comment by SwedzNet** [comment]
I do but it still got corrupted, corrupted being like all kinds of chisel blocks are replacing the common blocks...

**Comment by SwedzNet** [comment]
If I boot it up it just gets re-corrupted.

**Comment by SwedzNet** [comment]
The thing is, it's saying stuff about thaumcraft and I don't have that mod?

**Comment by TheCricket** [comment]
Chisel did not corrupt your world, you chose to view the part of the log that has nothing to do with it and refused to read the error that I print as severe that says that the log that you posted is absolutely irrelevant .
