### ISSUE TITLE
(2.5.1.44) Chisel 2 breaks Railcraft block sounds

### ISSUE THREAD

**Issue by TruePikachu** [TheCricket/Chisel-2#426]
See also [Railcraft's tracker](https://github.com/CovertJaguar/Railcraft/issues/655)

It appears that Chisel2 2.5.1.44 causes Railcraft 9.8.0.0 block sounds to break. I have not tested sounds from other parts of the mod.

When Chisel2 is installed, walking on e.g. Quarried Stone results in firing the (bad) SoundEvent `minecraft:step.railcraft`. CJ confirms that this ["isn't an actual sound, its a place holder tag that tells my sound processor to take over"](https://github.com/CovertJaguar/Railcraft/issues/655#issuecomment-154892697); however, this is being passed to the sound system without being handled by Railcraft.

Since adding Chisel 2 to the game is a trigger for this bug appearing, I have posted this issue here; it is possible that something on this end is causing the behavior.

**Comment by TheCricket** [comment]
The only sounds we touch are our own

**Comment by CovertJaguar** [comment]
My sound processor is here: https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/client/sounds/RCSoundHandler.java

It subscribes to the Forge sounds event and listens for any sound tag containing "railcraft". If something were to eat the event before Railcraft, it would not get a chance to play the correct sound.

**Comment by TruePikachu** [comment]
Looking at both the code here and OPIS output, I'm coming to the conclusion that Chisel2 itself isn't responsible for the behavior; it might be causing the issue to appear by changing the mod loading order, but it doesn't seem to be directly responsible.
Requesting close, possibly mark as invalid.

**Comment by TehNut** [comment]
Close it yourself? You opened it.

**Comment by TruePikachu** [comment]
I didn't see that button <_<
