### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Amphilohiy** [TheCricket/Chisel-2#427]
minecraft 1.7.10
forge 10.13.4.1448
chisel2 2.5.1.44 (via curse)

Minecraft crashing at startup. Tried without other mods.
Link to [logfile](http://pastebin.com/X4pVAS0C)

**Comment by TehNut** [comment]
Update Forge. #420

**Comment by Amphilohiy** [comment]
Thanks, that worked. Now i'm just embarrassed of myself.

**Comment by CptSpaceToaster** [comment]
Please close your issue if it's resolved.  Thank you!
