### ISSUE TITLE
[2.9.3.9] Target block disappears when chisel breaks

### ISSUE THREAD

**Issue by Belgabor** [TheCricket/Chisel-2#428]
If you have a block in the chisel's inventory as a target and chisel blocks in world, the target block(s) are destroyed if the chisel breaks.

**Comment by TheCricket** [comment]
I can work on this in the morning

**Comment by CptSpaceToaster** [comment]
Why is the block stored in the chisel a "real block"... can't it be a representation of the block that can't be "removed"?  Why do we allow players to store a block _in_ the chisel in the first place?

If make the block stored in the chisel a "representation" that can't be retrieved (that doesn't subtract from the user's inventory when they try to store the block in the chisel in the first place) then we would curb a lot of the duplication issues we've seen over the months.

**Comment by tterrag1098** [comment]
Then what would be used when crafting? That's the whole point of it.

**Comment by CptSpaceToaster** [comment]
The chisel would maintain a reference to the block, but unlike a bank/inventory slot where you deposit a block, and you have to retrieve the block later... the chisel just maintains an ethereal reference that can be destroyed with the chisel when it's all done.

I might be misunderstanding something here.

**Comment by TehNut** [comment]
What he means is how would the _crafting_ aspect of the Chisel work if you did that. Don't want to be turning ghost blocks into physical ones now, do we?

**Comment by CptSpaceToaster** [comment]
Oh... that takes place IN the chisel doesn't it......... I was thinking that took place in the 2x2 crafting square in the player's inventory for a moment.
