### ISSUE TITLE
[Suggestion] QOL connected texture improvements

### ISSUE THREAD

**Issue by Belgabor** [TheCricket/Chisel-2#429]
I've had this idea for a while but was reluctant to suggest it because it seems like a lot of work to implement. But if I don't spill it, nothing will ever come of it =)
The source of the idea is originally that there are several blocks in chisel that look like they should have connected textures but don't (I'm mostly looking at you limestone!). But now and then there are also situations where you don't want textures to connect for artistic or other reasons. There are ways to do that with other mods, but that can also be imperfect.

So here's what I'd suggest:
- All blocks with textures that don't naturally repeat or vary should have connected textures
- All such blocks exist in two states. Both look the same but only connect to those in the same state (but not the other)
- To switch state, simply put it in a crafting grid (like Enhanced Inventories does the alternate chests). Maybe also add a button to the chisel so you don't have to leave the interface to do it.
- Add a tool to switch state in world.

**Comment by tterrag1098** [comment]
This would effectively double the amount of IDs that chisel uses

**Comment by Belgabor** [comment]
Couldn't that be handled via NBT data?

**Comment by tterrag1098** [comment]
Blocks don't have NBT data

**Comment by TheCricket** [comment]
What is TOL? I mean if you want some of the limestone textures to have connected textures just say hey, I think these blocks would look really nice as connected textures. That is super easy to do and doesn't take any code at all.

**Comment by Belgabor** [comment]
Time of life, but I meant quality of life, so I fixed that.
The other stuff is mostly to satisfy other people. Not everybody might agree with what I think, so that would allow everybody to achieve the style they choose.
Personally I would think it awesome if limestone had connected textures. Currently it seems a bit inconsistent. The patterns are similar to other types of stone, but don't have connected textures like they do.

**Comment by Belgabor** [comment]
To explain a bit, having two states would for example allow you to make a pattern out of the same type of block, let's say a snaking pattern or for example a chessboard pattern with 2x2 "tiles".

**Comment by CptSpaceToaster** [comment]
having "two states" means that every block in chisel that would support this feature would need a block ID for an "Unconnected block" and another block ID for it's "connected version"

This would increase the number of block ID's we reserve by a significant margin, and we aren't too comfortable trying to push that number any further.  I like your idea, but it doesn't sound like we have a practical way of going about it.

(Making all blocks Tile Entities is also out of the question)

**Comment by Drullkus** [comment]
> All blocks with textures that don't naturally repeat or vary should have connected textures

lmao I'm not doing that

![http://www.reactiongifs.com/r/choofed.gif](http://www.reactiongifs.com/r/choofed.gif)

**Comment by Drullkus** [comment]
> Add a tool to switch state in world.

Thaumcraft has this weird thing where if you ward a Chisel block, it disconnects the CTM from the natural blocks, but it will connect to other CTM warded blocks. Use this instead.

**Comment by TheCricket** [comment]
oh damn that is useful

**Comment by tterrag1098** [comment]
Well that's technically a bug, he's just not implementing our interface.

**Comment by Drullkus** [comment]
I doubt he'd do that now since he's halted TC4.2 completely to move onto TC5

**Comment by TheCricket** [comment]
its a feature

**Comment by Drullkus** [comment]
> Bugs are just features you haven't yet befriended.

– [Bob Ross](https://twitter.com/BobRossGameDev)
