### ISSUE TITLE
ctm connected textures disabler

### ISSUE THREAD

**Issue by Fabboz** [TheCricket/Chisel-2#432]
Hello,
Is possible to disable the ctm textures so i can use only the "regular" block that don't connect each other?
will it be possible in the future?

thx bye

**Comment by TheCricket** [comment]
It is something I will be exploring in 1.8 no promises

**Comment by Fabboz** [comment]
I play on 1.7.10

**Comment by CptSpaceToaster** [comment]
If I recall correctly, there was a config option to disable _every_ CTM texture at some point... was that removed somewhere along the way?

**Comment by TheCricket** [comment]
No idea on that one Cpt, and Fabboz, I don't know what to tell you. I will be exploring it for 1.8 and that is all I can speak to right now

**Comment by CptSpaceToaster** [comment]
Yep... [it exists](https://github.com/Chisel-2/Chisel-2/blob/master/src/main/java/com/cricketcraft/chisel/config/Configurations.java#L93), but was silently broken somewhere along the way.

`disableCTM` does not appear to be referenced at all.

**Comment by Drullkus** [comment]
My blocks were designed to take full use of the connected texture experience. I do not recommend disabling it for the best visual experience.

**Comment by TheCricket** [comment]
Thanks every AAA publisher ever :P

**Comment by Drullkus** [comment]
Aaayy lmao

**Comment by alexbegt** [comment]
can i have a config option to disable the Drullkus part of this mod?

**Comment by TheCricket** [comment]
What mod, I thought we were making a texture pack

**Comment by Drullkus** [comment]
What texture pack, I thought we were making a money here

**Comment by TheCricket** [comment]
Nah we only get paid when we get on forgecraft Kappa

**Comment by alexbegt** [comment]
i thought this was for payday 2 and not minecraft

**Comment by Drullkus** [comment]
I thought we made money from tears of Optifine peasants

**Comment by TheCricket** [comment]
nah this is a fallout 4 mod

**Comment by Drullkus** [comment]
What is a fallout 4?

**Comment by CptSpaceToaster** [comment]
It's basically Minecraft with SEUS

**Comment by alexbegt** [comment]
It's basically the simpsons hit & run

**Comment by Drullkus** [comment]
What's a minecraft?

**Comment by CptSpaceToaster** [comment]
That's the non-Drullkus part of the mod

**Comment by Drullkus** [comment]
What's a Drullkus?

**Comment by CptSpaceToaster** [comment]
Scientists have not been able to answer that question, and remain puzzled _even to this day_.

**Comment by Drullkus** [comment]
Damn. I was wondering if _somebody_ knew :(

**Comment by tterrag1098** [comment]
Well, this stayed on topic. @CptSpaceToaster I suspect the reason is the CTMLib split. Not sure how to do a config for something like that, easily anyways.

**Comment by TheCricket** [comment]
I thought you knew us tterrag :P when have we ever stayed on topic

**Comment by CptSpaceToaster** [comment]
@tterrag1098 IIRC, A quick hack, would be to make [this](https://github.com/Chisel-Team/CTMLib/blob/56c10a6ff31e555920e85a6da1136d4e465a7e83/src/main/java/team/chisel/ctmlib/CTM.java#L103) return `{ 18, 19, 17, 16 }` every time.  Just pass in a boolean.

Otherwise, we could look into disabling the entire renderer... and using the default one somehow.
