### ISSUE TITLE
Startup crash with AE2_rv3_alpha_10

### ISSUE THREAD

**Issue by Zaflis** [TheCricket/Chisel-2#434]
> java.lang.NullPointerException: Cannot add variation in group AECertusQuartz for null block.
>   at team.chisel.carving.Carving.addVariation(Carving.java:160)
>   at team.chisel.Features$1.addBlocks(Features.java:64)

Full crashlog: http://pastebin.com/T2ttkTcJ

Temporary fix: Downgrade to AE2_rv3_alpha_9

Chisel-2.9.3.9.jar

**Comment by tterrag1098** [comment]
Why would you expect an AE2 alpha to work? They say it's not compatible with addons.

**Comment by TheCricket** [comment]
Logic
