### ISSUE TITLE
Some blocks loss texts and some aluminum stairs loss textures

### ISSUE THREAD

**Issue by DSLM** [TheCricket/Chisel-2#435]
Forge 10.13.4.1492
Chisel 2.5.1.44

![2015-12-02_22 04 01](https://cloud.githubusercontent.com/assets/12635058/11550960/b6942090-9942-11e5-8516-1b468d70fee6.png)
![2015-12-02_22 04 08](https://cloud.githubusercontent.com/assets/12635058/11550964/b69a6270-9942-11e5-8bed-c013aa02e2c6.png)
![2015-12-02_22 04 40](https://cloud.githubusercontent.com/assets/12635058/11550963/b69a619e-9942-11e5-98d5-5d6160f6742f.png)
![2015-12-02_22 04 49](https://cloud.githubusercontent.com/assets/12635058/11550961/b698d39c-9942-11e5-8363-4cf913fbdabd.png)
![2015-12-02_22 07 24](https://cloud.githubusercontent.com/assets/12635058/11550965/b69b9cc6-9942-11e5-8ec1-80ae33a2feae.png)
![2015-12-02_22 07 27](https://cloud.githubusercontent.com/assets/12635058/11550962/b698e2d8-9942-11e5-9d43-06a98e7f2ed2.png)
![2015-12-02_22 10 11](https://cloud.githubusercontent.com/assets/12635058/11550966/b6a95172-9942-11e5-9724-27084113ab7b.png)
![2015-12-02_22 10 22](https://cloud.githubusercontent.com/assets/12635058/11550967/b6b0d94c-9942-11e5-9c19-c4a723f50089.png)

**Comment by TheCricket** [comment]
Yep fixed in 1.8

**Comment by Ar97x** [comment]
This won't have a fix for 1.7.10? I have the same issue.

**Comment by Altairon73** [comment]
agree, really need a 1.7.10 fix for aluminium stairs please, as its affecting both inventory and actual world placement

**Comment by Drullkus** [comment]
I don't think the stairs are craftable in survival. :P

**Comment by Altairon73** [comment]
no but when placed in a creative world they are just ugly pink and black blocks

**Comment by TheCricket** [comment]
Its being dealt with
