### ISSUE TITLE
Missing Textures on Forge Microblocks Parts

### ISSUE THREAD

**Issue by EliteMasterEric** [TheCricket/Chisel-2#436]
![untitled](https://cloud.githubusercontent.com/assets/4635334/11611588/c22505a6-9ba3-11e5-97bb-9feac980614b.png)

This is not a problem with Optifine; it seems that many blocks with connected textures (like pillars) do not work as microblocks.

Other microblocks work fine.

**Comment by TheCricket** [comment]
I know its not a problem with optifine, its the fact that FMP doesn't like connected textures. Will be fixed in 1.8

**Comment by EliteMasterEric** [comment]
Thanks for acknowledging the issue :)
