### ISSUE TITLE
[Suggestion] More Pillars

### ISSUE THREAD

**Issue by EliteMasterEric** [TheCricket/Chisel-2#437]
Currently there are only a variety of pillars for Marble, Ice, and Sandstone, and one-ofs of some other materials.

I'd like to see more types of pillars, since they look really good when decorating.

In particular, I'd like to see several types of Cobblestone pillars; they'd go well with my current base.

**Comment by TheCricket** [comment]
ping @Drullkus

**Comment by ChrisMintjes** [comment]
Maybe something similar for wood? Maybe I have overlooked it a bit, but I don't think wooden pillars are a thing.

**Comment by Drullkus** [comment]
Some current wood variations can be used as pillars, but I will investigate

**Comment by EliteMasterEric** [comment]
Going through my old issues and found this. I'd mark it as resolved since I know Cobblestone has pillars (at least in the version I last played).
