### ISSUE TITLE
Can't chisel block of aluminum back to IE/TiCon block

### ISSUE THREAD

**Issue by misterhaan** [TheCricket/Chisel-2#439]
I was decorating with the shipping crate block of aluminum, but ended up with a few more than I needed.  I tried to chisel the extras back to the Industrial Engineering Block of Aluminium, but I only get the Chisel Aluminum Blocks.  NEI shows two pages of chisel recipes for Block of Aluminum and the second page includes the Chisel blocks plus the ones from IE and Tinker's Construct, but I get the first page which only has the Chisel blocks.  The other metal blocks only have one page in NEI.

Using the Iron Chisel from 2.5.1.44 in a custom mod pack using Forge 10.13.4.1566.

**Comment by Drullkus** [comment]
Try using [the latest version](http://minecraft.curseforge.com/projects/chisel/files)

**Comment by misterhaan** [comment]
I had verified I was using the latest version . . . but that was apparently Chisel 2 which isn't this.  Switched to this and the problem is gone plus everything I had done with Chisel 2 is still working.
