### ISSUE TITLE
Chisel 2 Error: Initializing minecraft mods

### ISSUE THREAD

**Issue by T-Hox** [TheCricket/Chisel-2#441]
Help Me! Please , I Found This Error!

Forge Mod Loader has found a problem with your minecraft installation
You have mod sources that are duplicate within your system
Mod Id : File name

chisel : Chisel2-2.5.1.44.jar
chisel : Chisel-1.7.10-1.5.7.jar

**Comment by Choonster** [comment]
You've installed Chisel 1.X and Chisel 2, this doesn't work since they're different versions of the same mod. Uninstall Chisel 1.x.

You may want to replace Chisel 2 with [Chisel - Chisel Team](http://minecraft.curseforge.com/projects/chisel), since that's an actively maintained fork of Chisel 2.

**Comment by T-Hox** [comment]
But the chisel 2 asks you to install the chisel 1

**Comment by TehNut** [comment]
No it doesn't?

**Comment by Drullkus** [comment]
It absolutely should not! Did you download from the Curseforge website?

**Comment by TheCricket** [comment]
it doesn't, if you download a mod that has ever had my name on it and its not on curseforge you are putting your computer at risk.
