### ISSUE TITLE
Using an Energised Voidstone as block camouflage will create an x-ray effect. 

### ISSUE THREAD

**Issue by Hypocrisy** [TheCricket/Chisel-2#442]
Basically, putting an Energised Voidstone into something that allows it to be camouflaged (such as Drawbridge, Advanced Player Detector, Cable Camouflage, etc) will create an x-ray effect and allow you to see through the map. 

![example](http://i.imgur.com/Pqma0Lt.png)

It doesn't happen with regular Voidstone so I'm sure it's due to the particle effect or whatever it is from the energized version not rendering while being used as a skin for other blocks. 

EDIT: Upon further testing, this doesn't seem to happen when EnderIO's Painting Machine paints a facade as an Energised Voidstone. Finding out how that handles re-skinning blocks might help. Also, using it with an Abstruse Platform from Botania just makes it see-through but not x-ray.

**Comment by TheCricket** [comment]
Its how the mod uses it
