### ISSUE TITLE
crash to windows when braking a block whith a Chisel block

### ISSUE THREAD

**Issue by jal21** [TheCricket/Chisel-2#444]
i was playing Post Finem whith fastcraft and optifine and i was getting a crash when i was trying to brake a transparent tecnile frame whith another one and my game crashed i did it 3 more time and got the same resolt
[crash-2016-01-30_09.34.07-client.txt](https://github.com/Chisel-2/Chisel-2/files/110919/crash-2016-01-30_09.34.07-client.txt)

**Comment by TheCricket** [comment]
You have optifine you get no help

**Comment by jal21** [comment]
ok

**Comment by Drullkus** [comment]
You forgot this, Cricket :)
