### ISSUE TITLE
Auto Chisel not accepting blocks in Target Slot

### ISSUE THREAD

**Issue by Pontiac76** [TheCricket/Chisel-2#445]
I'm playing with Chisel 2, for MC 1.7.10, under the Mod Pack Regrowth v1.8.8 in client/server mode.  The version of this mod is Chisel2-2.5.1.44.  The server console doesn't show any errors when I try to use it.  There might be something earlier, but I doubt it.

When trying to use the Auto Chisel, I can put the Obsidian Chisel in, I can put what item I want to convert from (Cobblestone), but I can't select anything to chisel to, or put anything in the Target Slot.  I have all upgrades, except the Reversion upgrade.

I've tried leaving the cobblestone on the chisel, to no effect, I've tried using nothing on the chisel, same result.

I looked the config, and I don't see anything obvious.  I tried in single user mode using Regrowth, and still no go.

I then went and created a brand new mod pack with JUST Chisel 2, single player, nothing else installed using Forge 10.13.4.1614, and I still can't add anything to the target slot.

I kicked up an old client/server world that is using Chisel2.3.10.37 and it works as expected.

Is there something I'm missing?

**Comment by Shona1984** [comment]
So i have the same issue and can't find a solution :(

**Comment by TheCricket** [comment]
1.7.10 is not being maintained

**Comment by Shona1984** [comment]
The moste reported issues are for 1.710 and it is not maintained anymore why?

**Comment by TheCricket** [comment]
Because 1.9 is
