### ISSUE TITLE
Missing Textures and more.

### ISSUE THREAD

**Issue by K4w4iiH4w4ii** [TheCricket/Chisel-2#447]
I'm using Chisel 2 for 1.8, and a lot of the textures are missing or broken. Here are some of the issues: glass panes are not transpercent and normal blocks, blocks missing one side, all slabs are full blocks and blocks missing all sides. These are not the only problems, some items are missing altogether and others not working. The chisel doesn't work, I must select the blocks manually out of the creative inventory and all the special items such as the Cloud in the Bottle and the Smashing Rock are not even present.

What could have possibly happened is thathat I downloaded an unofficial build, because I had trouble finding one for 1.8 (which is what I'm running because of the new blocks) and of course, these glitches occured. Does anybody have any insight on fixing the problem? thanks!

UPDATE: I tried the official 1.8.9 build, and I have the same problems. :/

UPDATE #2: Tried 1.7.10, no problems. I guess it's not fully updated and working. Please fix it.

**Comment by TheCricket** [comment]
Chisel 2 isn't for 1.8

**Comment by Drullkus** [comment]
[Get your latest Chisel builds here. 1.7.10 and 1.8.9.](http://minecraft.curseforge.com/projects/chisel/files)
