### ISSUE TITLE
Laboratory Blocks

### ISSUE THREAD

**Issue by Erozen777** [TheCricket/Chisel-2#449]
Has the animation from the Laboratory blocks information and direction consoles removed? They're the only textures that no longer move, all others fans, futura, and technical blocks are working without issue. 

Running;
Minecraft 1.7.10
Chisel 2 2.5.1.44
along with a list of other mods.

**Comment by TheCricket** [comment]
They never moved

**Comment by Erozen777** [comment]
My apologizes, I thought the screen used to scroll the information to the side of the block. Thank you for the response and the effort you all put into the mod, It's one of the reasons it has been on my short list of necessities whenever building my personal modpacks.

**Comment by Drullkus** [comment]
I... can make them move. We have the technology.

**Comment by Erozen777** [comment]
:D! That would be awesome, I'm basically trying to use the information console as rowed computer screens within a build I'm making would be awesome to have them line up horizontally and have the symbols written on them scroll to the side of the block. The full setup would feature a big computer with 2 rows of four the 2 rows could maintain the top and bottom edge of the block (Or if you want to make them connected textures I'll leave that as your call as neither design would ruin the build.) The rest of its usage will be multiple single user machines, more than like 6 in the same room as in and 35 more scattered throughout my map.

Please don't feel obligated I'm just suggesting at this point, and I'll understand if there are more pressing issues to make priority.
