### ISSUE TITLE
Chisel Dupe all block

### ISSUE THREAD

**Issue by Uzumachi02** [TheCricket/Chisel-2#451]
Shift clicking into full inventory
-- Edited by Cricket because you posted a public youtube video...

**Comment by TheCricket** [comment]
Don't upload that to be public next time

**Comment by Drullkus** [comment]
Tested and can confirm it works. ¯\_(ツ)_/¯

**Comment by TheCricket** [comment]
It makes sense. I just will test it in 1.9
