### ISSUE TITLE
crash client

### ISSUE THREAD

**Issue by Deefreez** [TheCricket/Chisel-2#454]
> [15:32:32] [Client thread/INFO]: Enabling Main Menu Mob render ticker
> [15:32:33] [Client thread/ERROR]: Couldn't render entity
> java.lang.NullPointerException
>   at com.cricketcraft.chisel.client.render.RenderChiselSnowman.renderEquippedItems(RenderChiselSnowman.java:48) ~[RenderChiselSnowman.class:?]
>   at com.cricketcraft.chisel.client.render.RenderChiselSnowman.func_77029_c(RenderChiselSnowman.java:32) ~[RenderChiselSnowman.class:?]
>   at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:213) [boh.class:?]
>   at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:23) [bok.class:?]
>   at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:11) [bok.class:?]
>   at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293) [bnn.class:?]
>   at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:276) [bnn.class:?]
>   at bspkrs.client.util.EntityUtils.drawEntityOnScreen(EntityUtils.java:186) [EntityUtils.class:?]
>   at bspkrs.bspkrscore.fml.BSMainMenuRenderTicker.onTick(BSMainMenuRenderTicker.java:101) [BSMainMenuRenderTicker.class:?]
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_166_BSMainMenuRenderTicker_onTick_RenderTickEvent.invoke(.dynamic) [?:?]
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
>   at cpw.mods.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:335) [FMLCommonHandler.class:?]
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:987) [bao.class:?]
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
>   at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
>   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
>   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
>   at net.launcher.components.T.run(net/launcher/components/T) [GorCraft.exe:?]
>   at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by TheCricket** [comment]
Fixed already
