### ISSUE TITLE
Serious dupe bug with Chisel and Thermal Expansion

### ISSUE THREAD

**Issue by SrAnthony** [TheCricket/Chisel-2#456]
Right click a Chisel and put any block/item do you want and close the GUI.
Right click with the chisel on a Cache and the Chisel GUI will open (with your items) and will save on cache. Move the items (from the GUI) to your inventory and remove the chisel on cache, you will receive a new chisel with the same items.

I can make a video if do you want.

**Comment by SrAnthony** [comment]
Oh, sorry, already fixed. Thanks.

**Comment by Brend-Smits** [comment]
This issue is still not fixed in this version. Running FTB Infinity Evolved (latest) 
Latest version of the mod in 1.7.10
