### ISSUE TITLE
Carpet blocks don't match

### ISSUE THREAD

**Issue by ghost** [TheCricket/Chisel-2#457]
I appreciate all the hard work done here and I am grateful. So, with a great deal of respect I would like to point out that some of the carpet colors don't match their description/materials. In particular, the purple carpet is red, maybe red-brown, and the red carpet is orange. I mean they're very pretty, but I went to put a royal purple carpet in my Thaumcraft area...
Thank you very much.

**Comment by TheCricket** [comment]
Is this in Chisel 3 or 2 because 2 is not being maintained

**Comment by ghost** [comment]
It's 2.9.4.10. Were the graphics redone in 3?

**Comment by TheCricket** [comment]
2.9.4 isn't my version. You should really only be using my version

**Comment by ghost** [comment]
I'm trying to figure out whose version is is. The launcher opens the curse page that lists TheCricket26 as the owner and lists Pokefenn as the 1.7.10 maintainer. Pokefenn's Chisel repository hasn't been updated in 2 years.
Either way, everyone's using the same texture files. Where can I find the texture credits/license? I was thinking of tweaking the colors to be consistent with the standard carpet either as a replacement or an alternate.

**Comment by TehNut** [comment]
You are using the [ChiselTeam](https://github.com/Chisel-Team/Chisel) version and you should continue to use it. It is updated farther than this version. As for tweaking the colors, you can use a Resource Pack. No need to worry about licensing, especially for private use.

**Comment by ghost** [comment]
Thanks for the info. I was going to offer the modified files, maybe as an alternate version.
