### ISSUE TITLE
Buggy asphalt

### ISSUE THREAD

**Issue by rzblue** [TheCricket/Chisel-2#462]
When walking over the asphalt version of concrete, I get "lagged" back to where I originally stepped on the asphalt. This makes walking on asphalt impossible for me. (by "lagged"  i mean it feels like really bad lag but it does it every time for more than a minute)

**Comment by Drullkus** [comment]
This... is weird. You should try [the latest version](http://minecraft.curseforge.com/projects/chisel/files) to see if the issue is still persisting.

**Comment by rzblue** [comment]
Thanks! I updated it and it fixed the issue.
