### ISSUE TITLE
Chisels model loader seems to affect my mod items?

### ISSUE THREAD

**Issue by BobyTheDragon** [TheCricket/Chisel-2#471]
So its is a strange title... yes... but I have no idea how to explain this.

I am a small mod author that knows very little java from a mod called Bobys Extras (Its a mod that started as a school project). As a last attempt i'm contacting you guys to see if you can help me. For some odd reason the first item in my mod is trying to load with your modelloader (I think at least) And its breaking the texture of my item. To be honest I have no clue what is going on and why its doing this. When I remove chisel though it acts normal and it loads properly.

Is there any way for me to stop the loader from attempting to load my items? 

Console spits this out: 
_[Client thread/ERROR] [FML]: Exception loading model for variant bobyex:ItemIronShardex#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception checking if model bobyex:item/ItemIronShardex can be loaded with loader team.chisel.client.render.ModelLoaderChisel@19cb3f, skipping_

if you need any more information just say.

**Comment by Drullkus** [comment]
Hi,

This repo is for a different Chisel, sorry about that. The Chisel you want is at https://github.com/Chisel-Team/Chisel

Also, want you want to do is to inherit the parent item model: https://github.com/Chisel-Team/CTM-Resources/blob/master/assets/minecraft/models/item/glass.json

**Comment by BobyTheDragon** [comment]
oh sorry I thought this was the proper one :P and thank you ill try the parent thing out
