### ISSUE TITLE
Chisel 2 marble, limestone being replaced by other mods blocks

### ISSUE THREAD

**Issue by ToddVee** [TheCricket/Chisel-2#55]
I found the server lagging as hell from time to time when people discover new regions, that is chunks.
The server even times out now and then, so I have to restart it.

After some testing I found out that is has to do with unusual blocks spawning here and there. Using worldedit, I disassebled the chunks that I found the suspicious blocks in completely.

I found IC2 copper blocks and machine blocks that, from the look and their location, should be marble and limestone. Here's a picture to visualize:

https://www.wuala.com/ToddVee/Minecraft/5.png/?key=k2nhdnUoE2bu

Note that at the chunk borders (in the non-affected chunks), the veins are perfectly fine. There seem to be some "affected" chunks.

Limestone is always IC2 machine block in affected chunks.
Marble is always IC2 copper block in affected chunks.
The red wool was IC2's UU-matter. I replaced it so it wouldn't flow all over.
There are also sandstone stairs where ore should be, or at least, where the stairs should not be, up until now I have no clue what that is supposed to mean.

I did not copy "old" regions onto this fairly new map.
I did not change the level.dat manually.
The one and only thing I did that is related to ore spawning was changing Thaumcrafts cinnabar ore spawn (enabled it). But I enabled/disabled ores in the past, on other maps and never encountered a problem like this. It doesn't mess up the ID mapping as far as I know.

**Comment by tterrag1098** [comment]
@ToddVee your links seem to have died. Could you please upload some screenshots to something more permanent like imgur?

**Comment by tterrag1098** [comment]
Pastebin is better for log files as well.

**Comment by tterrag1098** [comment]
This is most likely world corruption from a separate mod or other reason. Please, feel free to give more info but as it stands I'm going to close this for now.
