### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Xee1** [TheCricket/Chisel-2#70]
http://pastebin.com/xDy38LWf
Minecraft 1.7.10 latest version of Chisel.

**Comment by tterrag1098** [comment]
This is fixed.

**Comment by tterrag1098** [comment]
Actually there's a bug I missed, the TE registration for presents is inside a feature check for the auto chisel. I'll be fixing this shortly.

**Comment by Xee1** [comment]
Thanks @tterrag1098 !

**Comment by Xee1** [comment]
Ah another thing, the world added from multiworld had a different mapping id, because i've changed the entire world folder and id messed up

**Comment by CptSpaceToaster** [comment]
I'm not certain if we can help you recover...  were you asking for further support and assistance?

**Comment by Xee1** [comment]
For mapping id I fixed myself

**Comment by tterrag1098** [comment]
Oh this was definitely fixed. Closing.

**Comment by Xee1** [comment]
Thanks!
