### ISSUE TITLE
Feature request - Shift click to move stack to chisel input

### ISSUE THREAD

**Issue by tivec** [TheCricket/Chisel-2#77]
Heya! First I'd like to thank you so much for an awesome mod! 

One thing I find a bit annoying is that I can't shift click to move items to and from the chisel interface. Let's say I have a stack of marble, I would need to first click on the stack in my inventory, click on the input slot, then click on the result I want. Finally I have to click again to place it in my inventory.

It would be great to shift click - it would effectively cut out two clicks from the process :)

* Shift click on stack in inventory with chisel interface open: Stack is moved to input slot.
* Shift click on chiselled block in chisel interface: Move the stack directly to the first available inventory slot.

**Comment by CptSpaceToaster** [comment]
I think this was implemented last evening.  tterag, please confirm.

**Comment by tterrag1098** [comment]
Yes
