### ISSUE TITLE
Make road lines not be able to be destroyed in Adventure Mode with hand

### ISSUE THREAD

**Issue by Mitchellbrine** [TheCricket/Chisel-2#78]
It is possible for players to remove the road lines while in Adventure Mode. It is a great aesthetic for my map and I really like it, but it seems to take away from the map when the players can accidentally left click and the road lines pop off.

It'd be nice if they couldn't be destroyed without a tool in adventure mode. Thanks for all your great work on the mod. It's really incredible. Oh and say "Hi" to Drullkus for me.

-Mitchell

**Comment by warlordjones** [comment]
I'll look into this. Since they don't require a tool to break in survival, they by default can be broken without a tool in adventure mode. Not sure if this can be changed, but if it can I will!

**Comment by warlordjones** [comment]
Not sure this is possible without making road lines need a tool at all times - I can make them *able* to be broken, but not make them unable.
