### ISSUE TITLE
Present Boxes Work, but they are missing a "Non-Holiday" Texture

### ISSUE THREAD

**Issue by CptSpaceToaster** [TheCricket/Chisel-2#80]
We'll need to add 16 non-holiday textures, to coincide with the 16 present-box textures that we already have.

**Comment by warlordjones** [comment]
Agreed, and other people seem to agree too

**Comment by warlordjones** [comment]
I think it's decided they won't have a non-holiday texture

**Comment by CptSpaceToaster** [comment]
If there is to be no "non-holiday" texture, then the code looking for one will need to be removed.

**Comment by Drullkus** [comment]
Why not just comment it out for now?

Warlord jones should be online on IRC more often :(
