### ISSUE TITLE
Feature Request - Chiseled Ice to be made from Packed Ice to prevent melting.

### ISSUE THREAD

**Issue by Skiasvonski** [TheCricket/Chisel-2#82]
Chiseled Iceblock is still technically Ice so whenever any light is nearby, it melts.

**Comment by Skiasvonski** [comment]
Oh np! I thought It would be helpful if I added it to your github for you, wasn't trying to be pushy! thanks again

Date: Wed, 31 Dec 2014 09:21:03 -0800

**Comment by warlordjones** [comment]
Yup, no worries, it is quite useful to have it here. Also, it's added, I forgot to close this from the commit :P

**Comment by Skiasvonski** [comment]
You are the best, thanks again. It will be available in the next patch?

Date: Thu, 1 Jan 2015 03:06:07 -0800

**Comment by warlordjones** [comment]
Indeed

Arona
[+] You're welcome to add me to your address book
<https://ws.writethat.name/kwaga-bin/titan/WEB/me.pl/2040834221374130777/i>

**Comment by Skiasvonski** [comment]
Thanks! Done! Your work on this mod is excellent. I think in the long term, support for other Feed The Beast mods like ExtraTrees or Forestry would be awesome as well. I know it would be a ton of work, but if you ever need art assets, I do a bit of texturing myself.
Date: Thu, 1 Jan 2015 12:33:42 -0800
