### ISSUE TITLE
Feature Request - Colored Sand?

### ISSUE THREAD

**Issue by CptSpaceToaster** [TheCricket/Chisel-2#83]
Not sure if necessary or if it even fits in... but it was one of the first mods I ever made, and I think it ties in loosely:
![Colored Sand Recipe](http://i.imgur.com/cJpkr1u.gif?1?5307 "Colored Sand Recipe")

The class would need to extend BlockSand, as that's the easiest way to replicate the falling sand behavior, and I'll have to look at which methods I overrode the first time I did it.

It would be fitting if it smelted into vanilla's colored glass.

Really Old Link: https://github.com/CptSpaceToaster/CptsModdingGlass/blob/master/yamhaven/easycoloredglass/blocks/ColoredSandBlock.java

Further opens up the door, for colored sandstone, and it's chiseled variants (If there are any)

**Comment by warlordjones** [comment]
Why not xD
