### ISSUE TITLE
AntiBlocks

### ISSUE THREAD

**Issue by Drullkus** [TheCricket/Chisel-2#88]
Better name WIP

We should add a block that comes in all 16 colors. The textures ignore light mapping and have absolute color with no noise. They will have black outlines. Kinda like Antichamber :P

**Comment by CptSpaceToaster** [comment]
I intend to create 16 new blocks that will use the CTM renderer, and then extend the CTM renderer to disable the lightmap as it draws the blocks

Old calls will simply call the CTM renderer with the lightmap still enabled, but if we choose to disable it, we can do so)

ETA = I don't know when I'll be done with my lighting engine, and my OS is reinstalled... but after that.  This change isn't hard, and several others could tackle it if I'm too slow.

**Comment by CptSpaceToaster** [comment]
There was... what looked like an unused renderer that did nothing, but render a standard block.  So, I checked to see if anything used it... and I didn't see anything.  

I changed a line to remove the inclusion of a light value, and it should be good...

Now to make a block, and have it inplement the [new render type](https://github.com/TheCricket/Chisel-2/blob/df73373b9415a224ab6c640a1f444d94c4a95c55/src/main/java/com/cricketcraft/chisel/client/render/renderStandardBlock_noSunlight.java#L15)

**Comment by tterrag1098** [comment]
That class name ;_;

**Comment by CptSpaceToaster** [comment]
It's a wrpper... better name suggestions are welcome

**Comment by tterrag1098** [comment]
@TheCricket already changed it :P

**Comment by Drullkus** [comment]
It is implemented into the Dev branch. We should close this now.
