### ISSUE TITLE
Hex block texture problem

### ISSUE THREAD

**Issue by JadeCreeper** [TheCricket/Chisel-2#90]
When you have multiple Hex plating blocks adjacent (Vertically and horizontally) to each other, the hexagons do not line up with each other:
![hexBlocks](http://i.imgur.com/7fAc8WT.png)

**Comment by Kodos-Atoz** [comment]
THANK YOU! This has been eating at me for awhile, but I haven't had time to do up some textures like I mentioned I would in IRC.  Here's hoping a fix is in the works =)

**Comment by TheCricket** [comment]
Will be fixed along with #98

**Comment by Drullkus** [comment]
I uploaded the fixed textures. It's all up to Cricket now!
