### ISSUE TITLE
A lot of spam In my console

### ISSUE THREAD

**Issue by crunkazcanbe** [TheCricket/Chisel-2#91]
Dont know what it all means , but apparently this mod is conflicting with something . Log here http://pastebin.com/yWJ6zTi9

Thanx -Crunk

**Comment by TheCricket** [comment]
Duplicate of #84

**Comment by crunkazcanbe** [comment]
Thanx man sorry about the dup .

**Comment by TheCricket** [comment]
Not a problem. I registered a block that doesnt exist accidently, thats all this means. It is harmless
