### ISSUE TITLE
No FMP on Server

### ISSUE THREAD

**Issue by TheJulianJES** [TheCricket/Chisel-2#93]
Config on the server is okay, Chisel 2-2.2.1. Singleplayer FMP works!

**Comment by Nentify** [comment]
Also having this issue, a fix would be nice. Otherwise, if I add all the blocks to the microblocks list, will it be compatible with this config option when it's fixed?

Thanks!

**Comment by lilrichy** [comment]
I would also like this fixed. Adding the config to microblocks list works for some but not all blocks. Dont know if i'm just not using the right tile names or not for the rest. Any way of getting a full updated list of tiles to add to the config until this is fixed?
