### ISSUE TITLE
No glowey Hex blocks

### ISSUE THREAD

**Issue by JadeCreeper** [TheCricket/Chisel-2#98]
The hex plating blocks do not glow (Noted by both me and Soaryn on his stream today).

**Comment by TheCricket** [comment]
Will do it tonight

**Comment by Drullkus** [comment]
I uploaded new textures a few hours ago. Hopefully Cricket will see that I uploaded a grayscale texture that is meant to be used for the glow.

**Comment by warlordjones** [comment]
Fixed by Cricket for next version I believe.

**Comment by Drullkus** [comment]
I don't see the fixes yet

**Comment by CptSpaceToaster** [comment]
I made the texture brighter.

**Comment by tterrag1098** [comment]
/me pats @CptSpaceToaster on the head

:>

**Comment by CptSpaceToaster** [comment]
/me walks around in circles 3 times, and sits down smiling happily
